---
title: 'Calculating Probability'
Section: 'Probability'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human EEG data 

```{r EEG}
#load in the restingEEG dataset.
#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                            'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

ggplot(df, aes(x = pow_delta_O, 
               color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')

```

## What is the probability of having low, medium, or high delta power? 

```{r delta power probs}

cutOffLow = 15
cutOffHigh = 50
N = 

#what is the probibility of low delta power? 

#what is the probability of medium delta power

#what is the probability of high delta power






```

## If we randomly sample from EEG power, 
## what probabilities of low, medium, and high do we observe?  

```{r random sampling}

#randomly sample from our data
#make each sample the same size as the original sample

sampN = 100

sampleVals = rep(0,sampN)
for(ii in 1:sampN){

  sampleVals[ii] = 
}

sampDf <- data.frame( 
          low = ,
          med = , 
          high= ,
          type = c('observed', 'prob')) 


sampDf = sampDf %>%
          pivot_longer(cols = c(low, med, high), 
                       names_to = 'propGroup',
                       values_to = 'value')

sampDf %>% ggplot(aes(x = propGroup, y = value
                      ))+
  geom_bar( ) + 
  myTheme + brightCol + brightFil


```
