---
title: 'describing real data'
author: "Adam Dede"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## coin flipping multiplication rule 

```{r coin flipping}

#what is the probability of flipping heads 5 times in a row? 
.5*.5*.5*.5*.5
.5^5

#what is the probability of flipping heads 10 times in a row? 
.5^10

#let's make a graph of the probability
# Y axis = probability 
# X axis = number of heads in a row

probVals = data.frame(prob = .5^seq(1,8,1), 
                      runLen = seq(1,8,1))
probVals$dummy = as.factor(1)

ggplot(probVals, aes(x = runLen, y = prob, color = dummy)) + 
  geom_line(linewidth = 2) + myTheme + brightCol + 
  theme(legend.position = 'none')

```

## Do simulations of flipping coins match the multiplication rule outcomes?  

```{r simulated coin flips}


probVals$simRes = 0
tries = 100
for(numFlips in 1:8){
  flips = replicate(tries, sum(sample(c(0, 1), 
                    size = numFlips, replace = TRUE)))
  probVals$simRes[numFlips] = mean(flips == numFlips)
}


longVals <- probVals %>% pivot_longer(cols = c('prob', 'simRes'),
                          names_to = 'dataType', 
                          values_to = 'prob')

ggplot(longVals, aes(x = runLen, y = prob, color = dataType)) + 
  geom_line(linewidth = 2) + myTheme + brightCol

```

