---
title: 'Tails'
Section: 'Probability'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## sp500 historical change data load in 

```{r sp500}
df = read.csv(file.path(gitHubPath,
                        'data','SP500HistoricalData.csv'))
names(df)[6] <- 'Change'

df$Change = unlist(lapply(df$Change, 
                          function(x) 
                            as.numeric(strsplit(x, '%')[[1]])))

df$dummy = as.factor(1) 

ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)')

```

## What is the probability of having an extreme change? 

```{r two tails}
#set a threshold for "extreme" and visualize: 
extremeCut = 1.25
N = dim(df)[1]

df$extreme = df$Change > extremeCut |
             df$Change < -extremeCut

ggplot(df, aes(x = Change, color = extreme, fill = extreme)) +
  geom_histogram(breaks = seq(-2, 2, .25)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)')

#Two-tailed probability of an extreme change: 
sum(df$extreme) / N



```

## What is the probability of an extreme positive change?  

```{r positive tail}

#set a threshold for "extreme" and visualize: 
extremeCut = 1.25
N = dim(df)[1]

df$extreme = df$Change > extremeCut 

ggplot(df, aes(x = Change, color = extreme, fill = extreme)) +
  geom_histogram(breaks = seq(-2, 2, .25)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)')

#one-tailed probability of an extreme positive change: 
sum(df$extreme) / N


```

## What is the probability of an extreme negative change?  

```{r positive tail}

#set a threshold for "extreme" and visualize: 
extremeCut = -1.25
N = dim(df)[1]

df$extreme = df$Change < extremeCut 

ggplot(df, aes(x = Change, color = extreme, fill = extreme)) +
  geom_histogram(breaks = seq(-2, 2, .25)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)')

#One-tailed probability of an extreme negative change: 
sum(df$extreme) / N


```
