---
title: 'outliers'
author: "Adam Dede"
date: "2024-07-23"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)


gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'
library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))


```
## human EEG data 

```{r EEG}

df = read.csv(paste0(gitHubPath, 'data\\restingEEG.csv'))

df$dummy = as.factor(1)
df$idx = randsample(length(df$name), length(df$name)) 

ggplot(EEGdat, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

ggplot(EEGdat, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0,250,.5)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

ggplot(df, aes(x = idx, y = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_point() + 
  scale_y_log10() + 
  myTheme + brightCol + theme(legend.position = 'none')

```
## my emails per day 

```{r EEG}

df = read.csv(paste0(gitHubPath, 'data\\emailTimes.csv'))

df <- df %>% group_by(DayOfWeek, Month, DayOfMonth, Year) %>% 
  summarize(count = n())

df$dummy = as.factor(1) 

ggplot(df, aes(x = count, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0, 51, 1)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

```
## sp 500 daily change 

```{r sp 500}

df = read.csv(paste0(gitHubPath, 'data\\SP500HistoricalData.csv'))
names(df)[6] <- 'Change'

df$Change = unlist(lapply(df$Change, function(x) as.numeric(strsplit(x, '%')[[1]])))

df$dummy = as.factor(1) 

ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  xlab('Daily Change (%)')

```
## country garbage data
```{r country garbage example}

#import the country garbage data set and visualize the totalPop variable: 
wasteDat = read.csv(paste0(gitHubPath, 'data\\plasticWaste.csv'))

#first plot the histogram of country total populations 
wasteDat$dummy = as.factor(1)
wasteDat %>% ggplot(aes(x = totalPop, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightCol + brightFil + theme(legend.position = 'none')

mean(wasteDat$totalPop)
mean(wasteDat$totalPop[-which(wasteDat$totalPop > 500000000)])

```