---
title: 'identifying distributions '
author: "Adam Dede"
date: "2024-07-23"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)


gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'
library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))


```
## human EEG data 

```{r EEG}

df = read.csv(paste0(gitHubPath, 'data\\restingEEG.csv'))

df$dummy = as.factor(1) 

ggplot(df, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0, 250, .5)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

ggplot(df, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0, 50, .5)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = 16.22), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = 5.88), color = 'purple', linewidth =2) +
  geom_vline(aes(xintercept = 3), color = 'green', linewidth =2)

ggplot(df, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-25, 50, .5)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = 5.88), color = 'purple', linewidth =2) +
  geom_vline(aes(xintercept = 5.88 + 27.35), color = 'green', linewidth =2)+
  geom_vline(aes(xintercept = 5.88 - 27.35), color = 'green', linewidth =2)+
  geom_vline(aes(xintercept = 3.32), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = 15.71), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = 5.88 + 16.25), color = 'blue', linewidth =2)+
  geom_vline(aes(xintercept = 5.88 - 16.25), color = 'blue', linewidth =2)

analyticDists %>% filter(dist == 'empiricalData' | dist=='norm' | dist == 'logNorm') %>% ggplot(aes(x = xVal, y = density, color = dist)) + 
  geom_line(linewidth = 2) + brightCol + myTheme + 
  ggtitle("EEG data") + 
  # geom_vline(aes(xintercept = 15.71), color = '#20CDF2', linewidth =3) + 
  # geom_vline(aes(xintercept = 16.57), color = '#6EE11F', linewidth =2)  + 
  # geom_vline(aes(xintercept = 34.67), color = '#415d2e', linewidth =2) + 
  xlim(c(-5, 80))

quanDat = data.frame(empiricalData = quantile(df$pow_delta_O, seq(.05,.95,.05)), 
                     logNorm = qlnorm(seq(.05,.95,.05), meanlog = mean(log(df$pow_delta_O)), 
                    sdlog = sd(log(df$pow_delta_O))), 
                     norm = qnorm(seq(.05,.95,.05), mean = 16.22, sd = 27.36),
                     quant = seq(.05,.95,.05))

quanDat %>% ggplot(aes(x = norm, y = empiricalData, color = quant)) + 
  geom_point(size = 3) + myTheme +
  scale_color_gradientn(colors = c("lightgreen", "yellow", "lightcoral")) +
  geom_abline(slope = 1, intercept = 0, color = 'purple', linetype = 'dashed')+
  xlim(c(-10, 100)) + 
  ylim(c(-10, 100))

quanDat %>% ggplot(aes(x = logNorm, y = empiricalData, color = quant)) + 
  geom_point(size = 3) + myTheme +
  scale_color_gradientn(colors = c("lightgreen", "yellow", "lightcoral")) +
  geom_abline(slope = 1, intercept = 0, color = 'purple', linetype = 'dashed')+
  xlim(c(-10, 100)) + 
  ylim(c(-10, 100))

#what is 25% through the normal? 
qnorm(c(.25, .75), mean = 16.22, sd = 27.36)
quantile(df$pow_delta_O, c(.25, .75))


qlnorm(c(.25, .75), meanlog = mean(log(df$pow_delta_O)), 
                    sdlog = sd(log(df$pow_delta_O)))


```
## my emails per day 

```{r EEG}

df = read.csv(paste0(gitHubPath, '//data//emailTimes.csv'))

df <- df %>% group_by(DayOfWeek, Month, DayOfMonth, Year) %>% 
  summarize(count = n())

df$dummy = as.factor(1) 

ggplot(df, aes(x = count, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0, 51, 1)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = 13.45), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = 13), color = 'purple', linewidth =2) +
  geom_vline(aes(xintercept = 7), color = 'green', linewidth =2)

ggplot(df, aes(x = count, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0, 51, 1)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = 13), color = 'purple', linewidth =2) +
  geom_vline(aes(xintercept = 13 + 7.6), color = 'green', linewidth =2)+
  geom_vline(aes(xintercept = 13 - 7.6), color = 'green', linewidth =2)+
  geom_vline(aes(xintercept = 8), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = 18), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = 13 + 5.94), color = 'blue', linewidth =2)+
  geom_vline(aes(xintercept = 13 - 5.94), color = 'blue', linewidth =2)

```
## sp 500 daily change 

```{r sp 500}

df = read.csv(paste0(gitHubPath, '\\data\\SP500HistoricalData.csv'))
names(df)[6] <- 'Change'

df$Change = unlist(lapply(df$Change, function(x) as.numeric(strsplit(x, '%')[[1]])))

df$dummy = as.factor(1) 

ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  xlab('Daily Change (%)') + 
  geom_vline(aes(xintercept = .08), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = .10), color = 'purple', linewidth =2) +
  geom_vline(aes(xintercept = 0), color = 'green', linewidth =2)

ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  xlab('Daily Change (%)') +  
  geom_vline(aes(xintercept = .08), color = 'purple', linewidth =2) +
  geom_vline(aes(xintercept = .08 + .71), color = 'green', linewidth =2)+
  geom_vline(aes(xintercept = .08 - .71), color = 'green', linewidth =2)+
  geom_vline(aes(xintercept = -.31), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = .57), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = .08 + .55), color = 'blue', linewidth =2)+
  geom_vline(aes(xintercept = .08 - .55), color = 'blue', linewidth =2)

```
## human memory performance

```{r human memory}
df = read.csv(paste0(gitHubPath, 'data\\MemoryData.csv'))

df <- df %>% filter(TargALL_UVSD_d >=0)

#first plot the histogram of country total populations 
df$dummy = as.factor(1)
df %>% ggplot(aes(x = TargALL_UVSD_d, color = dummy, fill = dummy)) + 
  geom_histogram(bins = 10) + 
  myTheme + brightCol + brightFil + theme(legend.position = 'none')


```

