---
Title: 'Bar Plots'
Section: 'ggplot'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---

## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

# Load packages
library(tidyverse) # data manipulation and visualization
```

## Plot miles per gallon for all cars in the dataset

```{r bar plot}

mpg %>% ggplot(

#geom_bar defaults don't really make a "bar plot" 
mpg %>% ggplot(aes(x = model, y = hwy))+
  geom_bar(stat = ) 

#how are some of the values so high? 


```

## make a unique ID for each car

```{r unique cars}

df = mpg
df$uniqueID = paste()


#okay, but this plot is unreadable! 


```

## Summarize before plotting 

```{r sum plot}

plotVals = mpg %>% 
  


plotVals %>% ggplot(

  

```  
  
