---
title: 'correlation matrices'
Section: 'Correlation'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))

# Load package
library(corrplot)

```

## human EEG data 

```{r EEG}

#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                                'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)


```

## make a correlation matrix

```{r cor mat}


# Compute correlation matrix
cor_matrix <- cor(select(df, 
              colnames(df)[grepl("pow", colnames(df))]),
                  method = 'spearman') 

corrplot(cor_matrix, method = 'color', 
         type = "lower")


```

## correlation matrix averaged within frequencies 

```{r freq mat}
#group data by frequency 

#Separate region and frequency information from var names
freq_region_df <- rownames(cor_matrix) %>%
  data.frame(rowNameVals = .) %>%
  separate(rowNameVals, 
           into = c("prefix", "freq", "region"), 
           sep = "_")
#make a list of all combinations of frequency 
long_df <- expand.grid(Row_Freq = freq_region_df$freq, 
                       Col_Freq = freq_region_df$freq)
#put the correlation values in 
long_df$Correlation <- as.vector(cor_matrix)
#group by frequency combinations and average
freq_df = long_df %>% group_by(Row_Freq, Col_Freq) %>%
  summarize(corVal = mean(Correlation)) %>% ungroup()
#pivot wider and plot
freq_df = freq_df %>%
  pivot_wider(names_from = Col_Freq, 
              values_from = corVal) %>%
  select(-Row_Freq)  # Remove Row_Region

rownames(freq_df) = colnames(freq_df)  

freq_df = as.matrix(freq_df)


corrplot(freq_df, method = "color", 
         type = "lower")




```

## make correlation matrix averaged within region

```{r region mat}



freq_region_df <- rownames(cor_matrix) %>%
  data.frame(rowNameVals = .) %>%
  separate(rowNameVals, 
           into = c("prefix", "freq", "region"), 
           sep = "_")


long_df <- expand.grid(Row_Region = freq_region_df$region, 
                       Col_Region = freq_region_df$region)

long_df$Correlation <- as.vector(cor_matrix)

reg_df = long_df %>% group_by(Row_Region, Col_Region) %>%
  summarize(corVal = mean(Correlation))

reg_df = reg_df %>%
  pivot_wider(names_from = Col_Region, 
              values_from = corVal) %>%
  ungroup() %>%  # Ungroup to avoid automatic inclusion
  select(-Row_Region)  # Remove Row_Region

rownames(reg_df) = colnames(reg_df)  


reg_df = as.matrix(reg_df)

minVal = min(reg_df)
maxVal = max(reg_df)

corrplot(reg_df, method = 'color',
         type = "lower", 
         col.lim = c(minVal, maxVal), is.corr = F)


```