---
title: 'Correlation Scratch'
Section: 'Correlation'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)
library(readxl)

```

## ice cream sales and murder

```{r}
months = c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
             'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')

allMurders = read.csv(file.path(gitHubPath,
  'data/',
  'murderDatCombined.csv'))

allMurders %>% group_by(YEAR,MONTH) %>%
    summarize(murders = n()) -> allMurders

allMurders$dummy = as.factor(1)

allMurders %>% group_by(MONTH) %>% 
  summarize(meanMurders = mean(murders), dummy = unique(dummy)) %>%
  ggplot(aes(x = MONTH, y = meanMurders, color = dummy)) +
  geom_line(linewidth = 2) + 
  geom_jitter(data = allMurders, aes(x = MONTH, y = murders), size = 2) + 
  scale_x_continuous(
    breaks = seq(1,12),     # Custom tick positions
    labels = months  # Custom labels
  ) + 
  myTheme + brightCol + theme(legend.position = 'none')
  


```

## looking at murder and ice cream


```{r}


iceCreamDat = read.csv(file.path(gitHubPath, 'data',
                'IPN31152N.csv'))
iceCreamDat$MONTH = month(iceCreamDat$observation_date)
iceCreamDat$YEAR = year(iceCreamDat$observation_date)

allMurders <- merge(iceCreamDat, allMurders, 
                   by = c("YEAR", "MONTH"))
names(allMurders)[4] = 'iceCream'


allMurders %>% group_by(MONTH) %>% 
  summarize(meanIceCream = mean(iceCream), dummy = unique(dummy)) %>%
  ggplot(aes(x = MONTH, y = meanIceCream, color = dummy)) +
  geom_line(linewidth = 2) + 
  geom_jitter(data = allMurders, aes(x = MONTH, y = iceCream),
              size = 2) + 
  scale_x_continuous(
    breaks = seq(1,12),     # Custom tick positions
    labels = months  # Custom labels
  ) + 
  myTheme + brightCol + theme(legend.position = 'none')
 
allMurders %>% ggplot(aes(x = iceCream, y = murders, color = dummy)) + 
  geom_point(size = 3) + myTheme + brightCol + theme(legend.position = 'none') 

allMurders %>% ggplot(aes(x = iceCream, y = murders, color = dummy)) + 
  geom_point(size = 3) + myTheme + brightCol + theme(legend.position = 'none') +
  geom_vline(xintercept = mean(allMurders$iceCream), 
             color = 'red', linewidth = 2) + 
  geom_hline(yintercept = mean(allMurders$murders), 
             color = 'red', linewidth = 2)

meanMur = mean(allMurders$murders)
meanIce = mean(allMurders$iceCream)
n = length(allMurders$MONTH)
#top right
sum(allMurders$murders>meanMur & allMurders$iceCream>meanIce)
sum(allMurders$murders>meanMur & allMurders$iceCream>meanIce) / n

#top left
sum(allMurders$murders>meanMur & allMurders$iceCream<meanIce)
sum(allMurders$murders>meanMur & allMurders$iceCream<meanIce) / n

#bottom left
sum(allMurders$murders<meanMur & allMurders$iceCream<meanIce)
sum(allMurders$murders<meanMur & allMurders$iceCream<meanIce) / n

#bottom right
sum(allMurders$murders<meanMur & allMurders$iceCream>meanIce)
sum(allMurders$murders<meanMur & allMurders$iceCream>meanIce) / n

cor.test(allMurders$murders, allMurders$iceCream)

```


<!-- ## human EEG data -->

<!-- ```{r EEG} -->

<!-- #Key variable name: pow_delta_O -->
<!-- df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv')) -->

<!-- df$dummy = as.factor(1) -->
<!-- df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0) -->

<!-- df <- df %>% filter(age<(8*12)) -->

<!-- df$babyChild = df$age<50 -->
<!-- df$babyChild[df$babyChild] = 'baby' -->
<!-- df$babyChild[df$babyChild=='FALSE'] = 'child' -->



<!-- ``` -->

<!-- ## random sub sample of size 10 per group -->

<!-- ```{r random} -->
<!-- pvals = data.frame(tlog = rep(0,100), -->
<!--            t = rep(0,100), -->
<!--            wil = rep(0,100)) -->
<!-- for(ii in 1:100){ -->
<!-- set.seed(ii) -->

<!-- child = df$pow_delta_O[df$babyChild == 'child'] -->
<!-- baby = df$pow_delta_O[df$babyChild == 'baby'] -->

<!-- child = child[randsample(length(child), 10)] -->
<!-- baby = baby[randsample(length(baby), 10)] -->

<!-- res = t.test(log(child,10), log(baby,10)) -->
<!-- res2 = t.test(child, baby) -->
<!-- res3 = wilcox.test(child,baby) -->
<!-- pvals$tlog[ii] = res$p.value -->
<!-- pvals$t[ii] = res2$p.value -->
<!-- pvals$wil[ii] = res3$p.value -->
<!-- } -->

<!-- print(paste(sum(pvals$tlog<.05), 'of 100 for Log Transformed t-test')) -->
<!-- print(paste(sum(pvals$t<.05), 'of 100 for raw t-test')) -->
<!-- print(paste(sum(pvals$wil<.05), 'of 100 for Wilcoxon Rank Sum test')) -->


<!-- ``` -->


