---
title: 'Pearson Measures Linear'
Section: 'Correlation'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))


```

## human EEG data 

```{r EEG}

#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                                'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)


```

## try correlations with different age cut offs

```{r age cut off}

ggplot(df, aes(x =    , y =   , 
               color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightCol + 
  theme(legend.position = 'none') +
  xlab("age (months)")

ageCut = seq(12,1000,12)

ageVals =  
powVals =  
  
results = data.frame(  )
for(ii in 1:length(ageCut)){

  
}

ggplot(results, aes(x =  , y =  )) +
  geom_line(color = 'green') +
  myTheme + brightCol +
  xlab("cut off age (months)")

```

