---
title: 'Pearson Measures Linear'
Section: 'Correlation'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))


```

## human EEG data 

```{r EEG}

#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                                'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)


```

## try correlations with different age cut offs

```{r age cut off}

ggplot(df, aes(x = age, y = log(pow_delta_O,10), 
               color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') +
  xlab("age (months)")

ageCut = seq(12,1000,12)

ageVals = df$age
powVals = log(df$pow_delta_O)
results = data.frame(cutOff = ageCut, 
                     corVal = rep(0, length(ageCut)))
for(ii in 1:length(ageCut)){
  results$corVal[ii] = cor(powVals[ageVals<ageCut[ii]], 
                             ageVals[ageVals<ageCut[ii]])
}

ggplot(results, aes(x = cutOff, y = corVal)) +
  geom_line(color = 'green') +
  myTheme + brightFil + brightCol +
  xlab("cut off age (months)")

```

