---
title: 'Pearson Correlation'
Section: 'Correlation'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)
library(lubridate)

```

## ice cream sales and murder

```{r}
#homicide data from NYC: 
#https://www.nyc.gov/site/nypd/stats/
#                   reports-analysis/homicide.page

allMurders = read.csv(file.path(gitHubPath, 'data',
                'murderDatCombined.csv'))

allMurders %>% group_by(YEAR,MONTH) %>%
    summarize(murders = n()) -> allMurders

allMurders$dummy = as.factor(1)

  allMurders %>% ggplot(aes(x = MONTH, y = murders, 
                            color = as.factor(YEAR))) +
    geom_point()


```

## looking at murder and ice cream


```{r ice cream}
# https://fred.stlouisfed.org/series/IPN31152N
# Industrial Production: Manufacturing: Nondurable Goods: 
# Ice Cream and Frozen Dessert
iceCreamDat = read.csv(file.path(gitHubPath, 'data',
                'IPN31152N.csv'))
iceCreamDat$MONTH = month(iceCreamDat$observation_date)
iceCreamDat$YEAR = year(iceCreamDat$observation_date)

allMurders <- merge(iceCreamDat, allMurders, 
                   by = c("YEAR", "MONTH"))
names(allMurders)[4] = 'iceCream'
 
allMurders %>% ggplot(aes(x = iceCream, y = murders, 
                          color = dummy)) + 
  geom_point(size = 3) + myTheme + brightCol + theme(legend.position = 'none') 

write.csv(allMurders, file.path(gitHubPath,
  'data/',
  'murderDatCombined_iceCream.csv'))


```

## calculating Pearson Correlation 

```{r pearson}
#formula: r = (sum((x - meanX)*(y-meanY)) / n-1) / (sdX*sdY)
meanMur = mean(allMurders$murders)
meanIce = mean(allMurders$iceCream)
sdMur = sd(allMurders$murders)
sdIce = sd(allMurders$iceCream)
n = length(allMurders$murders)

covMurIce = sum((allMurders$iceCream - meanIce) * 
                (allMurders$murders - meanMur)) / (n-1)

r = covMurIce / (sdMur * sdIce)

print(paste('the correlation between ice cream production and murders in NYC is:',
            round(r, 3)))



```

## plotting murders and ice cream sales 

```{r plots}

months = c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 
             'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')

allMurders %>% group_by(MONTH) %>% 
  summarize(meanIceCream = mean(iceCream), dummy = unique(dummy)) %>%
  ggplot(aes(x = MONTH, y = meanIceCream, color = dummy)) +
  geom_line(linewidth = 2) + 
  geom_jitter(data = allMurders, aes(x = MONTH, y = iceCream),
              size = 2) + 
  scale_x_continuous(
    breaks = seq(1,12),     # Custom tick positions
    labels = months  # Custom labels
  ) + 
  myTheme + brightCol + theme(legend.position = 'none')

allMurders %>% group_by(MONTH) %>% 
  summarize(meanMurders = mean(murders), dummy = unique(dummy)) %>%
  ggplot(aes(x = MONTH, y = meanMurders, color = dummy)) +
  geom_line(linewidth = 2) + 
  geom_jitter(data = allMurders, aes(x = MONTH, y = murders), size = 2) + 
  scale_x_continuous(
    breaks = seq(1,12),     # Custom tick positions
    labels = months  # Custom labels
  ) + 
  myTheme + brightCol + theme(legend.position = 'none')



```

