---
title: 'Spearman Correlation Scratch'
Section: 'Correlation'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:/Users/Adam/Documents/GitHub/MasterStatsUsingR/'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)
library(readxl)

```

## human EEG data 

```{r EEG}

#Key variable name: pow_delta_O
df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)


```

## make a correlation function

```{r cor func}
myCor = function(x, y){
  meanX = mean(x)
  meanY = mean(y)
  sdX = sd(x)
  sdY = sd(y)
  n = length(x)
  
  covXY = sum((y - meanY) * 
              (x - meanX)) / 
          (n-1)
  
  r = covXY / (sdX * sdY)
  return(r)
}


```

## try correlations with different age cut offs

```{r age cut off}

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) +
  geom_point(size = 2) + 
  geom_smooth(method = "lm", formula = y ~ poly(x, 3), 
              color = "green", se = FALSE) +
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  xlab("age (months)")

ageCut = seq(12,1000,12)

ageVals = df$age
powVals = log(df$pow_delta_O)
results = data.frame(cutOff = ageCut, 
                     corVal = rep(0, length(ageCut)))
for(ii in 1:length(ageCut)){
  results$corVal[ii] = myCor(powVals[ageVals<ageCut[ii]], 
                             ageVals[ageVals<ageCut[ii]])
}

ggplot(results, aes(x = cutOff, y = corVal)) +
  geom_line(color = 'green') +
  myTheme + brightFil + brightCol +
  xlab("cut off age (months)")

```

## make a spearman correlation function

```{r spear func}

#run pearson code first!
#deal with ties! 
mySpear = function(x, y){
  x = rank(x)
  y = rank(y)
  d = x - y
  dSq = d^2
  n = length(x)
  r =1 - ( 6*sum(dSq) / 
    (n*(n^2-1)) )
 
  return(r)
}


```

## try correlations with different age cut offs Spearman

```{r age cut off spear}

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  xlab("age (months)")

ageCut = seq(12,1000,12)

ageVals = df$age
powVals = log(df$pow_delta_O)
results = data.frame(cutOff = ageCut, 
                     corPer = rep(0, length(ageCut)), 
                     corSpr = rep(0, length(ageCut)))
for(ii in 1:length(ageCut)){
  results$corSpr[ii] = mySpear(powVals[ageVals<ageCut[ii]], 
                             ageVals[ageVals<ageCut[ii]])
  results$corPer[ii] = myCor(powVals[ageVals<ageCut[ii]], 
                             ageVals[ageVals<ageCut[ii]])
}

results = results %>% pivot_longer(cols = c(corSpr, corPer),
                         names_to = 'corType',
                         values_to = 'corVal')

ggplot(results, aes(x = cutOff, y = corVal, color = corType)) +
  geom_line(linewidth = 2) +
  myTheme + brightFil + brightCol +
  xlab("cut off age (months)")

```
