---
title: 'describing distributions '
author: "Adam Dede"
date: "2024-07-14"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

courseThemePath = 
  "C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\courseTheme.R"

library(tidyverse) # data manipulation and visualization
source(courseThemePath)


```
## rolling a die

```{r rand sample}

df = data.frame('rollValue' = randsample(6, 10000, replacement = T))

df$dummy = as.factor(1) 

ggplot(df, aes(x = rollValue, color = dummy, fill = dummy)) + 
  geom_histogram(binwidth = 1) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

```
## heights

```{r rand heights}

df = data.frame('height' = rnorm(1000, mean = 175.3, sd = 5))

df2 = data.frame('height' = rnorm(1000000, mean = 175.3, sd = 5))

df$dummy = as.factor(1) 
df2$dummy = as.factor(2) 

ggplot(df, aes(x = height, color = dummy, fill = dummy)) + 
  geom_histogram(aes(y = ..count.. / sum(..count..)), binwidth = 1) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_freqpoly(data = df2, aes(y = ..count.. / sum(..count..)), 
                binwidth = 1, linewidth = 2) + 
  theme(axis.text.y = element_blank(),
        axis.ticks.y = element_blank(), 
        axis.title.y = element_blank())


ggplot(df, aes(x = height, color = dummy, fill = dummy)) + 
  geom_histogram(binwidth = 1) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(xintercept = mean(df$height) - sd(df$height), color = 'green', linewidth = 2) + 
  geom_vline(xintercept = mean(df$height) + sd(df$height), color = 'green', linewidth = 2)

sum(df$height > (mean(df$height) - sd(df$height)) & 
    df$height < (mean(df$height) + sd(df$height))   )
  



```
## incomes

```{r rand incomes}

df = data.frame('income' = rlnorm(1000, meanlog = log(60000), sdlog = 1))

df$dummy = as.factor(1) 

ggplot(df, aes(x = income, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

ggplot(df, aes(x = income, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')+ 
  geom_vline(xintercept = mean(df$income) - sd(df$income), color = 'green', linewidth = 2) + 
  geom_vline(xintercept = mean(df$income) + sd(df$income), color = 'green', linewidth = 2) + 
  geom_vline(xintercept = mean(df$income), color = 'green', linewidth = 2, linetype = 'dashed') 

sum(df$income > (mean(df$income) - sd(df$income)) & 
    df$income < (mean(df$income) + sd(df$income))   )
  

```
## Amazon orders

```{r rand orders}

df = data.frame('orders' = rpois(1000, lambda = 2))

df$dummy = as.factor(1) 

ggplot(df, aes(x = orders, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-.5,11.5, 1)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

```

## roller coaster data

```{r roller coaster}

df = data.frame('rollerCoasterSpeed' = c(81, 45, 76, 76, 89, 32, 35, 100, 105, 
                                         81, 81, 34, 90, 89, 90, 56, 137, 89, 
                                         81, 56))
df$deviation = df$rollerCoasterSpeed - mean(df$rollerCoasterSpeed)

sum(df$deviation[df$deviation>0])
sum(df$deviation[df$deviation<0])

df$squaredDeviation = (df$rollerCoasterSpeed - mean(df$rollerCoasterSpeed))^2

sum(df$squaredDeviation)

sum(df$squaredDeviation) / (length(df$rollerCoasterSpeed)-1)


sqrt(sum(df$squaredDeviation) / (length(df$rollerCoasterSpeed)-1))

sortedDF <- data.frame('sorted speeds' = sort(df$rollerCoasterSpeed),
           'idx' = 1:length(df$rollerCoasterSpeed))
df$dummy = as.factor(1) 

ggplot(df, aes(x = rollerCoasterSpeed, color = dummy, fill = dummy)) + 
  geom_histogram(binwidth = 10) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')


```
## dog breed data 
``` {r dog breeds}

df = data.frame('dogBreeds' = c("lab", "retriever", "lab", "lab", "bulldog", 
                                "beagle", "poodle", "poodle", "bulldog", 
                                "retriever", "lab", "retriever", "poodle", 
                                "bulldog", "beagle", "beagle", "lab", "poodle", 
                                "lab", "retriever"))


ggplot(df, aes(x = dogBreeds, color = dogBreeds, fill = dogBreeds)) + 
  geom_bar() + 
  myTheme + brightFil + brightCol 


```
## income example 

```{r income}

df = data.frame('income' = c(35, 40, 66, 38, 45, 150, 71, 20, 43, 15, 22, 85,
                             35, 900, 38, 19, 29, 110, 43, 35))
averages <- df %>% summarize(meanVal = mean(income), 
                            modeVal = Mode(income), 
                            medianVal = median(income))

df$income = sort(df$income)

mean(df$income)

median(df$income[1:10]) -> q25

median(df$income[11:20]) -> q75

median(df$income)

df$absDev = abs(df$income - mean(df$income))

sum(df$absDev)

sum(df$absDev) / 19 -> MADval

df$dummy = as.factor(1)
df %>% ggplot(aes(x = income, color = dummy, fill = dummy)) + 
  geom_histogram()+ 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  labs(x = 'income (thousands of dollars per year)') + 
  geom_vline(aes(xintercept = averages$meanVal), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = averages$medianVal), color = 'purple', linewidth =2) +
  geom_vline(aes(xintercept = averages$meanVal - sd(income)), color = 'red', linewidth =1, linetype = 'dotted') +
  geom_vline(aes(xintercept = averages$meanVal + sd(income)), color = 'red', linewidth =1, linetype = 'dotted') +
  geom_vline(xintercept = q25, color = 'purple', linewidth =1, linetype = 'dotted') +
  geom_vline(xintercept = q75, color = 'purple', linewidth =1, linetype = 'dotted') +
  geom_vline(aes(xintercept = averages$meanVal - MADval), color = 'green', linewidth =1, linetype = 'dotted') +
  geom_vline(aes(xintercept = averages$meanVal + MADval), color = 'green', linewidth =1, linetype = 'dotted')  

```

## grade example 

```{r grade}

df = data.frame('grades' = c(95, 76, 85, 98, 99, 20, 87, 92, 90, 78, 94, 87, 
                             91, 93, 91, 79, 84, 88, 90, 96))
averages <- df %>% summarize(meanVal = mean(grades), 
                            modeVal = Mode(grades), 
                            medianVal = median(grades))

df$dummy = as.factor(1)
df %>% ggplot(aes(x = grades, color = dummy, fill = dummy)) + 
  geom_histogram(binwidth = 5)+ 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = averages$meanVal), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = averages$modeVal), color = 'green', linewidth =3) + 
  geom_vline(aes(xintercept = averages$medianVal), color = 'purple', linewidth =2) 

```
## height example 

```{r height}

df = data.frame('heights' = c(68, 62, 63, 71, 73, 68, 65, 68, 65, 69, 65, 66, 
                              70, 64, 72, 67, 69, 68, 68, 70
))

averages <- df %>% summarize(meanVal = mean(heights), 
                            modeVal = Mode(heights), 
                            medianVal = median(heights))

df$dummy = as.factor(1)
df %>% ggplot(aes(x = heights, color = dummy, fill = dummy)) + 
  geom_histogram(binwidth = 2)+ 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = averages$meanVal), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = averages$modeVal), color = 'green', linewidth =3) + 
  geom_vline(aes(xintercept = averages$medianVal), color = 'purple', linewidth =2) 

```
## simulation example

```{r height}

df = data.frame('simulatedData' = round(rlnorm(100000, log(10,10))))

averages <- df %>% summarize(meanVal = mean(simulatedData), 
                            modeVal = Mode(simulatedData), 
                            medianVal = median(simulatedData))

df$dummy = as.factor(1)
df %>% ggplot(aes(x = simulatedData, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-.5,19.5,1))+ 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = averages$meanVal), color = 'red', linewidth =2) +
  geom_vline(aes(xintercept = averages$modeVal), color = 'green', linewidth =2) + 
  geom_vline(aes(xintercept = averages$medianVal), color = 'purple', linewidth =2) +
  theme(
    axis.text.y = element_blank()) 

```
## simulation example 2

```{r sim2}

df = data.frame('simulatedData' = round(rnorm(100000)))

averages <- df %>% summarize(meanVal = mean(simulatedData), 
                            modeVal = Mode(simulatedData), 
                            medianVal = median(simulatedData))

df$dummy = as.factor(1)
df %>% ggplot(aes(x = simulatedData, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-4.5,5.5,1))+ 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = averages$meanVal), color = 'red', linewidth =4) +
  geom_vline(aes(xintercept = averages$modeVal), color = 'green', linewidth =3) + 
  geom_vline(aes(xintercept = averages$medianVal), color = 'purple', linewidth =2) +
  theme(
    axis.text.y = element_blank()) 

```
## simulation example 3

```{r sim3}

df = data.frame('simulatedData' = round(rpois(100000, lambda = 3)))

averages <- df %>% summarize(meanVal = mean(simulatedData), 
                            modeVal = Mode(simulatedData), 
                            medianVal = median(simulatedData))

df$dummy = as.factor(1)
df %>% ggplot(aes(x = simulatedData, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-.5,10.5,1))+ 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = averages$meanVal), color = 'red', linewidth =3) +
  geom_vline(aes(xintercept = averages$modeVal), color = 'green', linewidth =2) + 
  geom_vline(aes(xintercept = averages$medianVal), color = 'purple', linewidth =2) +
  theme(
    axis.text.y = element_blank()) 

```
## simulation example 4

```{r sim4}

df = data.frame('simulatedData' = c(round(rnorm(95000, 69,1.5),1),
                                    round(rnorm(100000, 65,1.5),1)))

averages <- df %>% summarize(meanVal = mean(simulatedData), 
                            modeVal = Mode(simulatedData), 
                            medianVal = median(simulatedData))

df$dummy = as.factor(1)
df %>% ggplot(aes(x = simulatedData, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(55.5,80.5,.1))+ 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  geom_vline(aes(xintercept = averages$meanVal), color = 'red', linewidth =3) +
  geom_vline(aes(xintercept = averages$modeVal), color = 'green', linewidth =2) + 
  geom_vline(aes(xintercept = averages$medianVal), color = 'purple', linewidth =2) +
  theme(
    axis.text.y = element_blank()) 

```
## main simulation 
```{r sim from 4 dists}

sampSize = 10000

df = data.frame('norm' = rnorm(sampSize, 3, 1),
                'lnorm' = rlnorm(sampSize,log(3), 1), 
                'unif' = runif(sampSize,-2, 8),
                'pois' = rpois(sampSize, lambda = 3))

df <- df %>% pivot_longer(cols = c(names(df)), 
                   values_to = 'observed', 
                   names_to = 'dist')

df %>% ggplot(aes(x = dist, y = observed,  fill = dist)) + 
  geom_boxplot(color = 'pink') + myTheme  + brightFil + 
  ylim(c(-3, 10))

df %>% ggplot(aes(x = observed, color = dist)) + 
  geom_freqpoly(breaks = seq(-3.5,10.5, 1), linewidth = 3) + myTheme + brightCol + 
  xlim(c(-3, 10))

```