---
title: 'simulating data from different distributions'
Section: 'Simulating Data from Distributions'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## simualte data from a normal or gaussian distribution

```{r dataframe}

dat = 

ggplot(



```
## simulate data from a uniform distribution 
```{r uniform distribution}
#useful for simulating random probabilities 


dat = 

ggplot(



```

## simulate data from a log normal distribution

```{r log normal distribution}
#useful for modeling things like income 
dat = 

ggplot(


```

## simulate data from a poisson distribution
```{r poisson distribution}
#useful for modeling events like receiving emails! 
dat = 

ggplot(


```

