---
title: 'variability parametric'
author: "Adam Dede"
date: "2024-07-21"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

courseThemePath = 
  "C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\courseTheme.R"

library(tidyverse) # data manipulation and visualization
source(courseThemePath)
library(pracma) #practical numerical math functions (needed for Mode)

```

## simualte data from all four distributions we know

```{r simulate data}

sampSize = 10000

df = data.frame('norm' = rnorm(sampSize, 3, 1),
                'lnorm' = rlnorm(sampSize,log(3), 1), 
                'unif' = runif(sampSize,-2, 8),
                'pois' = rpois(sampSize, lambda = 3))

df <- df %>% pivot_longer(cols = c(names(df)), 
                   values_to = 'observed', 
                   names_to = 'dist')


```
## let's work with just the normal distribution data for now, start with plotting
```{r plot norm dist}

p <- df %>% filter(dist == 'norm') %>%
  ggplot(aes(x = observed, group = dist, color = dist, fill = dist)) + 
  geom_freqpoly(breaks = seq(-1, 7, .1), linewidth = 3) + 
  myTheme + brightCol + brightFil 

print(p) 
```
## calculate the standard deviation for the normal distribution

``` {r norm analysis}

normDat = df$observed[df$dist == 'norm'] 

#what's the mean value? 
# mean = sum(x) / length(x) 
sum(normDat) / length(normDat) -> meanVal
  
#what are the squared deviations from the meanVal? 
(normDat - meanVal)^2 -> squaredDevs
  
#what's the average squared Dev?  
sum(squaredDevs) / (length(squaredDevs)-1) -> variance

#square root it
sqrt(variance) -> sd


# Add vertical lines for central tendency measures
p + geom_vline(xintercept = meanVal, linetype = 'solid', size = 3, color = 'red') + 
    geom_vline(xintercept = meanVal+sd, linetype = 'dotted', size = 3, color = 'red') + 
    geom_vline(xintercept = meanVal-sd, linetype = 'dotted', size = 3, color = 'red')


```
## calculate the standard deviation for other distributions using the builtin function sd()

``` {r builtin calculations}

#calculate key values: 
df  %>%
  group_by(dist) %>%
  summarise(mean_val = mean(observed),
            sd_val = sd(observed),
            sd1 = sd_val + mean_val, 
            sdminus1 = meanVal - sd_val) -> builtinAvg 

#pivot longer to facilitate plotting
builtinAvg <- builtinAvg %>% 
              pivot_longer(cols = -c('dist'), 
                           names_to = 'type', 
                           values_to = 'stat')

df %>% ggplot(aes(x = observed, color = dist)) + 
  geom_freqpoly(breaks = seq(-1.5, 8, 1), linewidth = 2) + 
  facet_grid(dist~.) + myTheme + brightCol -> p

p + geom_vline(data = filter(builtinAvg, type != 'sd_val'),
               aes(xintercept = stat, linetype = type), 
               size = 3, color = 'red') +
  scale_linetype_manual(values = c('solid', 'dotted', 'dotted')) + 
  theme(axis.title.y = element_blank(), 
        axis.text.y = element_blank(), 
        axis.ticks.y = element_blank())


```

