---
title: 'Variability Non-Parametric'
Section: 'Simulating Data from Distributions'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)
library(kableExtra)


```

## simualte data from all four distributions we know

```{r simulate data}

sampSize = 10000

df = data.frame('norm' = rnorm(sampSize, 3, 1),
                'lnorm' = rlnorm(sampSize,log(3), 1), 
                'unif' = runif(sampSize,-2, 8),
                'pois' = rpois(sampSize, lambda = 3))

df <- df %>% pivot_longer(cols = c(names(df)), 
                   values_to = 'observed', 
                   names_to = 'dist')


```

## let's work with just the normal distribution data for now, start with plotting

```{r plot norm dist}

p <- df %>% filter(dist == 'norm') %>%
  ggplot(aes(x = observed, group = dist, color = dist, fill = dist)) + 
  geom_freqpoly(breaks = seq(-1, 7, .1), linewidth = 3) + 
  myTheme + brightCol + brightFil 

print(p) 
```

## calculate the range of the data

``` {r norm range}

normDat = df$observed[df$dist == 'norm'] 

#what's the max value

  
#what's the min value

  
#what's the max - min = range 



# Add vertical lines for the range
p + geom_vline(xintercept = minVal, linetype = 'solid', 
               size = 3, color = 'red') + 
    geom_vline(xintercept = maxVal, linetype = 'solid', 
               size = 3, color = 'red') 


```

## calculate the inter quartile range

``` {r norm IQR}

normDat = sort(normDat)

#25th percentile first quartile

#75th percentile third quartile


# Add vertical lines for the interquartile range
p + geom_vline(xintercept = q25, linetype = 'solid', size = 3, 
               color = 'red') + 
    geom_vline(xintercept = q75, linetype = 'solid', size = 3, 
               color = 'red') 
  

#alternatively box plots show the IQR by default: 
ggplot(data = 

```

## calculate the mean absolute deviation 

``` {r norm MAD}

#MAD = sum(abs(x - mean(x))) / (n-1)

#mean val


#absolute deviations


#sum and divide 


# Add vertical lines for the mad
p + geom_vline(xintercept = meanVal +madVal, 
               linetype = 'solid', size = 3, color = 'red') + 
    geom_vline(xintercept = meanVal - madVal, 
               linetype = 'solid', size = 3, color = 'red') 


```

## use summarize to get all the descriptive stats we know in one shot! 

```{r descriptives}





```
