---
title: 'variability parametric'
Section: 'Simulating Data from Distributions'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))


```

## simualte data from all four distributions we know

```{r simulate data}

sampSize = 10000

df = data.frame('norm' = rnorm(sampSize, 3, 1),
                'lnorm' = rlnorm(sampSize,log(3), 1), 
                'unif' = runif(sampSize,-2, 8),
                'pois' = rpois(sampSize, lambda = 3))

df <- df %>% pivot_longer(cols = names(df), 
                          names_to = 'dist', 
                          values_to = 'value')


```
## let's work with just the normal distribution data for now, start with plotting
```{r plot norm dist}

p <- df %>% filter(dist == 'norm') %>%
  ggplot(aes(x = value, group = dist, color = dist, 
             fill = dist)) + 
  geom_freqpoly(breaks = seq(-1, 7, .1), linewidth = 3) + 
  myTheme + brightCol + brightFil 

print(p) 
```
## calculate the standard deviation for the normal distribution

``` {r norm analysis}

normDat = df$value[df$dist == 'norm'] 

#what's the mean value? 
# mean = sum(x) / length(x) 
  

#what are the squared deviations from the meanVal? 

  
#what's the average squared Dev?  


#square root it


# Add vertical lines for central tendency measures
p + 

```
## calculate the standard deviation for other distributions using the builtin function sd()

``` {r builtin calculations}

#calculate key values: 
builtinAvg = df  %>%
              group_by(dist) %>%
              summarise(mean_val = mean(value),
                        
                        )
                        
                  

#pivot longer to facilitate plotting
builtinAvg <- builtinAvg %>% 
              pivot_longer(

p = df %>% ggplot(
  

p + 


```

