---
Title: 'Probability of a Sample'
Section: 'Z-test'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(BSDA)
library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## heights of basketball players 

```{r data}
#basketball player heights
df = data.frame('heights' = c(72,74,76,80,78,73,73,71,78,81,75,75,79,77,79))



```

## do a z-test 

```{r z test}

n = length(df$heights)

#step 1: Are NBA players drawn from the same height distribution 
#        as the overall population?

#step 2: 
#       NULL: 
M = 70
S = 4
#       ALTERNATE: 
# not the null 

#step 3: 
#       ALPHA:
alpha = .05
#       critical z value: 
critVal = abs(qnorm(alpha/2))
#       critical threshold values: 
lowerBound = M - critVal * (S / sqrt(n))
upperBound = M + critVal * (S / sqrt(n))

#step 4: 
m = mean(df$heights)

#step 5: 
if (m>upperBound | m<lowerBound){
  print('mean value is more extreme than critical threshold!')
} else { 
  print('mean value is not more extreme than critical threshold!')
}

#step 6: 
#What does the result in step 5 mean for answering our original question? 


z.test(df$heights, mu = M, sigma.x = S)



```

