---
Title: 'Sample Size and Error Rate'
Section: 'Z-test'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## Imagine we know the True population values for all distributions! 

```{r data}
#basketball player heights
M_NBA = 76

#Basketball FAN heights
M_fan = 70

#overall distribution of heights statistics: 
M = 70
S = 4

alpha = .05

```

## What is the probability of Type II error for NBA players? 

```{r NBA type II}

sampSize = seq(1,15,1)
runs = 1000

simRes = data.frame('sampMean' = rep(0,runs*length(sampSize)),
                    'sig' = rep(0,runs*length(sampSize)),
                    'n' = rep(0, runs*length(sampSize)))
simi = 1
for(n in sampSize){
  for(ii in 1:runs){
    samp = rnorm(n, M_NBA, S)
    critVal = qnorm(1-alpha/2)
    simRes$sampMean[simi] = mean(samp)
    simRes$sig[simi] = (mean(samp) - M)/(S/sqrt(n)) > critVal
    simRes$n[simi] = n
    simi = simi + 1
  }
}

# simSummary = data.frame(
#           sim_type_II = unlist(lapply(sampSize, function(n) {
#               1 - mean(replicate(runs, 
#                         mean(rnorm(n, M_NBA, S)) > 
#                           qnorm(.975, M, S/sqrt(n)) 
#               )) }
#           )),
#           n = sampSize
#         )

simSummary = simRes %>% group_by(n) %>% 
  summarize(sim_typeII = 1-mean(sig)) 

simSummary %>%
  ggplot(aes(y = sim_typeII, x = n, color = as.factor(1))) + 
  geom_line(linewidth=2) + 
  myTheme + brightCol + theme(legend.position = 'none')






```

## analytical type II error rate 

```{r NBA type II analytical}

#probability of retaining the null if sample size = 1
critVal = qnorm(1-alpha/2, M, S)

#what's the probability of an NBA player shorter than the critical value? 
typeII = pnorm(critVal, M_NBA, S)

#can you write this for all sample sizes in one line? 
# pnorm(critVal, M_NBA, standardError)

simSummary$analytic_typeII = pnorm(
                            qnorm(1-alpha/2, M, S/sqrt(sampSize)), 
                            M_NBA, S/sqrt(sampSize))

simLong = simSummary %>% pivot_longer(cols = 
                                c(sim_typeII, analytic_typeII),
                            names_to = 'calculation_source',
                            values_to = 'type_II_error')

simLong %>% ggplot(aes(x = n, y = type_II_error, 
                       color = calculation_source)) +
  geom_line() + myTheme + brightCol
  

```

## What is the probability of Type I error for NBA fans?   

```{r fan type I}


sampSize = seq(1,15,1)
runs = 1000

simRes = data.frame('sampMean' = rep(0,runs*length(sampSize)),
                    'sig' = rep(0,runs*length(sampSize)),
                    'n' = rep(0, runs*length(sampSize)))
simi = 1
for(ii in 1:runs){
  for(n in sampSize){
    samp = rnorm(n, M_fan, S)
    critVal = qnorm(1-alpha/2)
    simRes$sampMean[simi] = mean(samp)
    simRes$sig[simi] = abs((mean(samp) - M)/(S/sqrt(n))) > critVal
    simRes$n[simi] = n
    simi = simi + 1
  }
}



simSummary = simRes %>% group_by(n) %>% 
  summarize(sim_typeI = mean(sig)) 

simSummary %>%
  ggplot(aes(y = sim_typeI, x = n, color = as.factor(1))) + 
  geom_line(linewidth=2) + 
  myTheme + brightCol + theme(legend.position = 'none')



```

## analytical type I error rate  

```{r fan type I analytical}
#probability of retaining the null if sample size = 1
critVal = qnorm(1-alpha/2, M, S)

#what's the probability of an NBA fan taller than the critical value? 
typeI = 1-pnorm(critVal, M_fan, S)

#can you write this for all sample sizes in one line? 
# 1-pnorm(critVal, M_fan, standardError)

simSummary$analytic_typeI = 1-pnorm(
                      qnorm(1-alpha/2, M, S/sqrt(sampSize)), 
                            M_fan, S/sqrt(sampSize))

simLong = simSummary %>% pivot_longer(cols = 
                              c(sim_typeI, analytic_typeI),
                            names_to = 'calculation_source',
                            values_to = 'type_I_error')

simLong %>% ggplot(aes(x = n, y = type_I_error, 
                       color = calculation_source)) +
  geom_line() + myTheme + brightCol


```

