---
title: 'Using Across in Summarize'
Section: 'Tidying Data'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


Data can be found here: 
https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-05-21


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)


# Load packages

library(tidyverse) 
library(janitor) #helps to rename titles
```

## Load Data in and use janitor to make names R appropriate

```{r load data}

# Load the data 
#coastal vs mismanaged waste
cw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv")


# inspect the data 
head(cw)
names(cw)
cw <- clean_names(cw)
names(cw)


```

## rename variables with hard coding to make them easier to work with

```{r make easier names}

names(cw)
colnames(cw) <- c('country', 'countryCode', 'year', 'mismanagedTotal',
                  'coastalPop', 'totalPop')
names(cw)
  
```

## Group data by year and check # observations for each year

```{r summarizing}


#The tidyverse provides a simpler way to do it: 
results2 <- cw %>%
  group_by(year) %>%
  summarize(naCount = sum(is.na(mismanagedTotal)),
            count = n()) %>% 
  mutate(goodCount = count - naCount)



```

## Looks like only one year has any data! 

```{r cutting down to only one year}

cw = cw %>% filter(!is.na(mismanagedTotal))

#check if there was really only one observation per year for all countries

countryCounts = cw %>%
  group_by(country) %>%
  summarize(n = n())

max(countryCounts$n)



```

## Combining Summarize with specific column selection

```{r selective summary}

#what if I want the average value for every column? 
averageVals = vector('numeric', length(names(cw)))
#code from last time:                     
numCol = vector('logical', length(names(cw)))
for(ii in 1:length(names(cw))){
  numCol[ii] = is.numeric(cw[[ii]])
}
print(numCol)


print(averageVals)



#let's do it with the tidyverse to make it faster: 



```
