---
title: 'Data From Internet'
Section: 'Tidying Data'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


Data can be found here: 
https://github.com/rfordatascience/tidytuesday/tree/master/data/2019/2019-05-21


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)


gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")
# Load packages

library(tidyverse) 

```

## Load Data in and use janitor to make names R appropriate

```{r load data}

# Load the data 
#coastal vs mismanaged waste
cw <- read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-21/coastal-population-vs-mismanaged-plastic.csv")


# inspect the data 
head(cw)
names(cw)



```
