---
title: 'Importing CSVs'
Section: 'Importing Data'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization


```

## human EEG data 

```{r EEG}
#load in the restingEEG dataset. 
#There are a lot of variables in this dataset

#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, "data", 
                               "restingEEG.csv"))


hist(df$pow_delta_O[df$pow_delta_O < 250])
```

## sp 500 daily change 

```{r sp 500}


df = read.csv(file.path(gitHubPath, "data", 
                               "SP500HistoricalData.csv"))

names(df)
#let's simplify the name of column 6
names(df)[6] <- 'Change'

mode(df$Change)
# Initialize an empty numeric vector to store the cleaned values
cleaned_values <- numeric(length(df$Change))

# Loop through each element in df$Change
for (ii in 1:length(df$Change)) {
  # Remove the percent sign and convert to numeric
  cleaned_values[ii] <- as.numeric(
          strsplit(df$Change[ii], '%')[[1]])
}

# Assign the cleaned values back to the dataframe
df$Change <- cleaned_values


hist(df$Change)

```


