---
title: 'A Whole Import and Tidying pipeline!'
Section: 'Importing Data Into R'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output: 
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## Set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization



```

## Import data on Obesity Risk

```{r import}
#data source: https://data.cdc.gov/Chronic-Disease-Indicators/U-S-Chronic-Disease-Indicators/hksd-2xuw/about_data
df = read.csv(file.path(gitHubPath, 'data', 
                'U.S._Chronic_Disease_Indicators.csv'))
```

## Examine what data are available for later analysis

```{r choose data}
#Goals: 
#We want to predict cardiovascular disease!
#relevant Questions 
#overall Stratification1
#age-adjusted DataValueType
#Questions need short names
#Select only relevant columns
#pivot wider 
#averaging over years within each state

```

## Choose a variable that we're going to want to predict

```{r cardio var choice}

#We want to predict cardiovascular disease!
names(df)

unique(df$Topic)

unique(df$Question[df$Topic == "Cardiovascular Disease"])
#"Diseases of the heart mortality among all people,
# underlying cause" looks good!

```



## Choose the useful questions

```{r useful Qs}
#relevant Questions 
#what stuff do we think will be likely to cause 
#or predict or be associated with heart disease mortality? 

#start with the target Question we already picked: 
goodVars = c()

unique(df$Topic)

#check sleep questions: 


#check mental health questions: 


#check tobacco questions: 


#check nutrition, physical activity, and weight questions: 


#check alcohol questions: 


#check oral health questions: 


#check social questions: 


#check cognitive health and caregiving questions: 



goodVars


```

## Rename the long form questions 

```{r rename}

#Questions need short names!!

#long versions of questions
longNames <- goodVars

shortNames = c()

# Check that lengths match
if(length(longNames) == length(shortNames)){
  print('all good!')
} else { 
  print('length mismatch!')
  }

# Create a named vector: 
#names are long strings, values are short names
name_map <- shortNames
names(name_map) = longNames

# Add the short version to the df
df <- df %>% 

```

## Simple filtering and selecting goals

```{r filter and select}

#overall Stratification1
df <- df %>% filter(StratificationCategory1 == 'Overall')

#age-adjusted DataValueType
df = df %>% filter(grepl("Age-adjusted",
                                  DataValueType))

#Select only relevant columns 
df <- df %>% select(YearStart, LocationAbbr, 
                    LocationDesc, DataValue,
                    DataValueType, Question_short) 
```

## Pivot wider so all the info about each state is on one row

```{r pivot wider}

#pivot Wider 
df_wide <- df %>%
  pivot_wider(
    id_cols = c(YearStart, LocationAbbr, 
                LocationDesc),
    names_from = Question_short,
    values_from = DataValue
  ) 

```

## Simplify by averaging over years

```{r simplify}
#average over years within each state to get one estimate: 
df_summary <- df_wide %>%
 


```

## Save for later

```{r save}

write.csv(df_summary, file.path(gitHubPath, 'data', 
                'cardioData_sum.csv'))

```