---
Title: 'Probability of a Sample'
Section: 'Z-test'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## simulate to show t-distribution

```{r data}

normDat = dnorm(seq(-5,5,.01))
tDat = dt(seq(-5,5,.01), 2)

df = data.frame('norm' = normDat, 
                't' = tDat,
                'x' = seq(-5,5,.01))

df <- df %>% pivot_longer(cols = c('norm', 't'),
                          names_to = 'dist',
                          values_to = 'density')

df%>% ggplot(aes(x = x, y = density, color = dist)) + 
  geom_line(linewidth = 2) + myTheme + brightCol+ 
  geom_vline(xintercept = qt(.975, 2),linewidth = 2, color = '#6EE11F')+
  geom_vline(xintercept = qt(.025, 2), linewidth = 2,color = '#6EE11F') + 
  geom_vline(xintercept = 1.96,linewidth = 2, color = '#20CDF2')+
  geom_vline(xintercept = -1.96, linewidth = 2,color = '#20CDF2')
  

normDat = dnorm(seq(-4,4,.01))
tDat = dt(seq(-4,4,.01), 10)

df = data.frame('norm' = normDat, 
                't' = tDat,
                'x' = seq(-4,4,.01))

df <- df %>% pivot_longer(cols = c('norm', 't'),
                          names_to = 'dist',
                          values_to = 'density')

df%>% ggplot(aes(x = x, y = density, color = dist)) + 
  geom_line(linewidth = 2) + myTheme + brightCol

df%>% ggplot(aes(x = x, y = density, color = dist)) + 
  geom_line(linewidth = 2) + myTheme + brightCol + 
  geom_vline(xintercept = qt(.975, 10), linewidth = 2, color = '#6EE11F')+
  geom_vline(xintercept = qt(.025, 10), linewidth = 2,color = '#6EE11F') + 
  geom_vline(xintercept = 1.96, linewidth = 2,color = '#20CDF2')+
  geom_vline(xintercept = -1.96, linewidth = 2,color = '#20CDF2')

normDat = dnorm(seq(-4,4,.01))
tDat = dt(seq(-4,4,.01), 100)

df = data.frame('norm' = normDat, 
                't' = tDat,
                'x' = seq(-4,4,.01))

df <- df %>% pivot_longer(cols = c('norm', 't'),
                          names_to = 'dist',
                          values_to = 'density')

df%>% ggplot(aes(x = x, y = density, color = dist)) + 
  geom_line(linewidth = 2) + myTheme + brightCol + 
  geom_vline(xintercept = qt(.975, 100),linewidth = 2, color = '#6EE11F')+
  geom_vline(xintercept = qt(.025, 100), linewidth = 2,color = '#6EE11F') + 
  geom_vline(xintercept = 1.96, linewidth = 2,color = '#20CDF2')+
  geom_vline(xintercept = -1.96, linewidth = 2,color = '#20CDF2')

```

#plot the L1 and L5 memory values

```{r L1 L5 mem}

df = read.csv(paste0(gitHubPath, 'data\\MemoryData.csv'))

df <- df %>% filter(TargALL_UVSD_d >=0)

df = df %>% select(c('L1cor_UVSD_d', 'L5_UVSD_d')) %>%
  pivot_longer(cols = c('L1cor_UVSD_d', 'L5_UVSD_d'),
               names_pattern = '(L1|L5)*',
               names_to = 'lag',
               values_to = 'd')

#first plot the histogram of country total populations 

df %>% ggplot(aes(x = d, color = lag, group = lag)) + 
  geom_freqpoly(bins = 8, linewidth = 2) + 
  myTheme + brightCol + brightFil

```

