---
title: 'Chi Square independence, brain data!'
author: "Adam Dede"
date: "2024-06-02"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
courseThemePath = 
  "C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\courseTheme.R"
source(courseThemePath)

```

## data for reactive channels

```{r dataframe}

brainDat = data.frame('region'  = c('ACC', 'dlPFC', 'Hip', 'PHG', 'pPFC'), 
                      'total'   = c(44, 247, 40, 79, 35), 
                      'reactive'= c(21, 133, 21, 54, 30))



```

## Visualize: controlling for total channels, 
## are there more reactive channels in some regions than others?

```{r visualize total and reactive}

brainLong = pivot_longer(brainDat, cols = c(total, reactive), 
                         names_to = "type", values_to = "chans")

brainLong %>% ggplot(aes(x = region, color = region, fill = type, 
                         y = chans))+
  geom_bar(stat = 'identity', size = 3) +  brightFil + myTheme


```

## Visualize: proportions to help intuition 
```{r visualize again}

brainDat$propReact = brainDat$reactive / brainDat$total

brainDat %>% ggplot(aes(x = region, color = region, fill = region, 
                          y = propReact))+
  geom_bar(stat = 'identity') +  brightCol + brightFil + myTheme


```

## Test independence:  
```{r independence test by hand}

numReg = length(brainDat$region)
#what's the column total for total channels? 
totChannels = sum(brainDat$total)
#what's the column total for reactive channels?
totReact = sum(brainDat$reactive)
#what's the total of all observations? 
totAll = totChannels + totReact
#what's the region sum within each region? 
brainDat$regSum = brainDat$total + brainDat$reactive
#get the expected values
brainDat$totalExpected = brainDat$regSum * totChannels / totAll
brainDat$reactiveExpected = brainDat$regSum * totReact / totAll
#calculate the chi squared contribution for each cell
brainDat$chiSquareTotal = (brainDat$total - brainDat$totalExpected)^2/
                          brainDat$totalExpected
brainDat$chiSquareReact = (brainDat$reactive - brainDat$reactiveExpected)^2/
                          brainDat$reactiveExpected

#get the total test stat and do the significance test: 
testStat = sum(brainDat$chiSquareTotal) + sum(brainDat$chiSquareReact)
numConditions = 2 
degreesOfFreedom = (numReg - 1) * (numConditions - 1)

critVal = qchisq(.95, degreesOfFreedom)
pVal = 1 - pchisq(testStat, degreesOfFreedom)

if(critVal < testStat){
  print('there is significant variability between total channels across regions')
  print(paste('chiSq =', testStat, '; DF =', degreesOfFreedom, 'p-value =', pVal))
} else {
  print('there is not variability between total channels across regions')
  print(paste('chiSq =', testStat, '; DF =', degreesOfFreedom, 'p-value =', pVal))
}

chisq.test(brainDat[,2:3])


```


