---
title: 'Making Predictions'
Section: 'Single Predictor Linear Regression'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))


```

## human EEG data 

```{r EEG}

df = read.csv(file.path(gitHubPath, 'data',
                          'restingEEG.csv'))
#dummy for plotting
df$dummy = as.factor(1) 
#outlier threshold
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

#filter data to look only at children up to 18 years old
df <- df %>% filter(age<(18*12))

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')


```

## human EEG by age

```{r age}

#let's pull out our key variables: 
age = df$age
pow = log(df$pow_delta_O,10)

#key formulas: 
#y' = bx + a
#b = r*(SDy/SDx)
#a = MEANy - b*MEANx



#add trend line to the plot using geom_abline: 
ggplot(df, aes(x = age, 
               y = log(pow_delta_O,10), 
               color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') 




```

## Let's make some predictions

```{r predictions}

#what do we predict for a 4-year-old
#y' = bx + a
pred4 = 

print(paste0('A 4-year-old will most likely have a log(deltaPow) of: ',
             round(pred4,2)))


```

## A limitation of regression: how does this do out into adulthood? 

```{r predictions adult}

df = read.csv(file.path(gitHubPath, 'data',
                                  'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

#replot: 


```

## What if we did our regression with adults and kids all included from the start?

```{r regression adult}





#replot it


```
