---
title: 'Regressing Out Age'
Section: 'Single Predictor Linear Regression'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human EEG data 

```{r EEG}

df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

df = df[df$group == 'CON' | df$group == "AD",]

t.test(log(df$pow_delta_O[df$group == 'AD'],10), 
       log(df$pow_delta_O[df$group == 'CON'],10))

df <- df %>% filter(age<(18*12))

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

t.test(log(df$pow_delta_O[df$group == 'AD'],10), 
       log(df$pow_delta_O[df$group == 'CON'],10))


```

## human EEG by age

```{r age}





t.test(log(df$pow_delta_O[df$group == 'AD'],10), 
       log(df$pow_delta_O[df$group == 'CON'],10))

age.lm = lm(log(pow_delta_O,10) ~ age+sex+group , data = df)
aovTab = Anova(age.lm, type = 3)


ei = which(row.names(aovTab) == 'Residuals')
ri = which(row.names(aovTab) == 'group')
print(paste0('eta squared: ', aovTab$`Sum Sq`[ri] /
            (aovTab$`Sum Sq`[ri] + aovTab$`Sum Sq`[ei])))


age.lm = lm(log(pow_delta_O,10) ~ age+sex , data = df)
df$delta_O_residuals = age.lm$residuals
t.test(df$delta_O_residuals[df$group == 'AD'], 
       df$delta_O_residuals[df$group == 'CON'])

meanAD = mean(df$delta_O_residuals[df$group == 'AD'])
meanCON = mean(df$delta_O_residuals[df$group == 'CON'])

SS_AD = sum((df$delta_O_residuals[df$group == 'AD'] - meanAD)^2)
SS_CON = sum((df$delta_O_residuals[df$group == 'CON'] - meanCON)^2)

n_AD = length(df$delta_O_residuals[df$group == 'AD'])
n_CON = length(df$delta_O_residuals[df$group == 'CON'])

Spooled = sqrt( ( (SS_AD + SS_CON) / (n_AD+n_CON-2) )) 

(meanAD - meanCON) / Spooled

#So, there's an interesting point here: a huge d in the residualized space 
#and a tiny eta squared in the overall space. What this says is that the 
#variability caused by age and sex is much larger than the variability caused
#by diagnosis. Does something being significant in the residualized space have
#meaning if the variability left in that residualized space is really small? 


ggplot(df, aes(x = delta_O_residuals, color = group)) +
  geom_freqpoly(size = 2) +
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

ggplot(df, aes(x = group, y = delta_O_residuals, color = group)) +
  geom_boxplot() +
  myTheme + brightFil + brightCol

```

## Let's make some predictions

```{r predictions}

#what do we predict for a 4-year-old
pred4 = 48*b+a

print(paste0('A 4-year-old will most likely have a log(deltaPow) of: ',
             round(pred4,2)))


```

## A limitation of regression: how does this do out into adulthood? 

```{r predictions adult}

df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  geom_abline(slope = b, intercept = a, color = 'red', size = 2) 


```

## What if we did our regression with adults and kids all included from the start?

```{r regression adult}

#let's pull out our key variables: 
age = df$age
pow = log(df$pow_delta_O,10)

#key formulas: 
#y' = bx + a
#b = r*(SDx/SDy)
#a = MEANy - b*MEANx

#get key values: 
ageMean = mean(age)
powMean = mean(pow)

ageSD = sd(age)
powSD = sd(pow)

r = cor(age, pow)

#plug into formulas:
bnew = r*(powSD / ageSD)
anew = powMean - bnew*ageMean

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  geom_abline(slope = b, intercept = a, linetype = 'dashed', 
              color = 'red', size = 2) +
  geom_abline(slope = bnew, intercept = anew, color = 'red', size = 2) 



meanAD = mean(log(df$pow_delta_O[df$group == 'AD'],10))
meanCON = mean(log(df$pow_delta_O[df$group == 'CON'],10))

SS_AD = sum((log(df$pow_delta_O[df$group == 'AD'],10) - meanAD)^2)
SS_CON = sum((log(df$pow_delta_O[df$group == 'CON'],10) - meanCON)^2)

n_AD = length(log(df$pow_delta_O[df$group == 'AD'],10))
n_CON = length(log(df$pow_delta_O[df$group == 'CON'],10))

Spooled = sqrt( ( (SS_AD + SS_CON) / (n_AD+n_CON-2) )) 

(meanAD - meanCON) / Spooled

```
