 ---
title: 'Significance Testing Regression'
Section: 'Single Predictor Linear Regression'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))

```

## human EEG data 

```{r EEG}

df = read.csv(file.path(gitHubPath, 'data',
                          'restingEEG.csv'))
#dummy for plotting
df$dummy = as.factor(1) 
#outlier threshold
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

#filter data to look only at children up to 18 years old
df <- df %>% filter(age<(18*12))

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')


```

## human EEG by age regression

```{r regression builtin}

#use R's builtin function to fit the regression:
pow.age = lm(log(pow_delta_O, 10) ~ age, data = df)

summary(pow.age)

```

## Doing a significance test on a regression

```{r sig test}

#Step 1: is delta power predicted by age? 

#step 2: Null: There is no linear relationship between age and delta power
#        Alternative: age predicts delta power

#step 3: Use degrees of freedom to establish critical F-ratio
dfreg = 1 #number of predictors 
dferr = length(df$age) - dfreg - 1
Fcrit = qf(.95, df1 = dfreg, df2 = dferr) #qf takes two df arguments: df1 is numerator

#step 4: calcualte F ratio for the regression

#SS values 
SSerr = sum(pow.age$residuals^2)
yMean = mean(log(df$pow_delta_O,10))
SStotal = sum((log(df$pow_delta_O,10) - yMean)^2)
SSreg = SStotal - SSerr

#get F ratio: 
Fratio = (SSreg / dfreg) / (SSerr / dferr)

#step 5: compare F ratio observed to critical value
#AND step 6: provide interpretation to answer the question
if(Fratio > Fcrit){
  print(cat("The observed F ratio of", round(Fratio,2), 
               "is greater than F critical of", round(Fcrit,2),
               ".\n Age significantly predicts delta power"))
} else{
  print(cat("The observed F ratio of", round(Fratio,2), 
               "is NOT greater than F critical of", round(Fcrit,2),
               ".\n No evidence that age predicts delta power"))
}

#compare to builtin output: 
summary(pow.age)



```

