---
title: 'Describing Real Data'
Section: 'Determining Distribution'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)

```

# load data that we previously cleaned and organized
```{r load plastic waste data}

df = read.csv('G:\\My Drive\\Teaching\\stats\\RCourse\\cleanData\\plasticWaste.csv')


```

## human EEG data 

```{r EEG}
#load in the restingEEG dataset. There are a lot of variables in this dataset
#for this analysis let's just focus on the delta power in the occipital region 
#of the head. 
#Key variable name: pow_delta_O
df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

ggplot(df, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

ggplot(df, aes(x = log(pow_delta_O,10), color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

df <- df %>% filter(age<(8*12))

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')


```

## human EEG babies vs. kids

```{r t test split}


df$babyChild = df$age<50
df$babyChild[df$babyChild] = 'baby'
df$babyChild[df$babyChild=='FALSE'] = 'child'

ggplot(df, aes(x = log(pow_delta_O,10), color = babyChild)) + 
  geom_freqpoly(linewidth = 2) + myTheme + brightCol

t.test(log(df$pow_delta_O[df$babyChild=='baby'],10),
       log(df$pow_delta_O[df$babyChild=='child'],10))

```

## human EEG by age

```{r age}


df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

df <- df %>% filter(age<(18*12))

age = df$age
pow = log(df$pow_delta_O,10)

ageMean = mean(age)
powMean = mean(pow)

ageSD = sd(age)
powSD = sd(pow)

r = cor(age, pow)

b = r*(powSD / ageSD)
a = powMean - b*ageMean


ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  geom_abline(slope = b, intercept = a, color = 'red', size = 2) 


ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  geom_abline(slope = b, intercept = a, color = 'red', size = 2) 



set.seed(13)

subDF = df[sample(length(df$age), 10),]

ggplot(subDF, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 3) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  geom_abline(slope = b, intercept = a, color = 'red', size = 2, linetype = 'dashed') + 
  geom_hline(yintercept = powMean, linetype = 'dashed', color = 'green', size = 2)

# + 
#   geom_vline(xintercept = ageMean, linetype = 'dashed', color = 'green', size = 2) + 
#   geom_hline(yintercept = powMean, linetype = 'dashed', color = 'green', size = 2) 

cor.test(df$age, log(df$pow_delta_O, 10))



```

## regression without intercept

```{r no int}

pow.age = lm(log(pow_delta_O,10) ~ age + 0, data = df)

b = pow.age$coefficients[[1]]
a = 0

ggplot(df, aes(x = age, y = log(pow_delta_O,10), color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') +
  geom_abline(slope = b, intercept = a, color = 'red', size = 2) 

ggplot(data.frame('residuals' = pow.age$residuals, 
                  'dummy' = as.factor(1)), 
       aes(x = residuals, fill = dummy)) + 
  geom_histogram() + brightFil + myTheme + 
  theme(legend.position = 'none')

ggplot(data.frame('residuals' = pow.age$residuals, 
                  'age' = df$age, 
                  'dummy' = as.factor(1)),
      aes(x = age, y = residuals, color = dummy))+
  geom_point(size = 2) + brightCol + myTheme + 
  theme(legend.position = 'none') + 
  geom_hline(yintercept = 0, color = 'red')


```

## showing different R2 strengths

```{r}

# Parameters

rho <- 0.7  # desired correlation

corSim <- function(rho){ 
  n = 500
# Step 1: Generate two independent standard normal variables
x <- rnorm(n)
z <- rnorm(n)

# Step 2: Create y as a linear combination of x and z
y <- rho * x + sqrt(1 - rho^2) * z

dat = data.frame(x = x, y = y, dummy = as.factor(1))

outPlot <- dat %>% ggplot(aes(x = x, y = y, color = dummy)) + 
  geom_point(size = 2) + brightCol + 
  myTheme + 
  geom_smooth(method = 'lm', se = F, 
              color = 'red', linetype = 'dashed', linewidth = 2) + 
  labs(x = NULL, y = NULL) + 
  theme(legend.position = 'none',
        axis.text.x = element_blank(), 
        axis.text.y = element_blank()) + 
  ggtitle(paste0('Rho = ', rho))

return(outPlot)
}

for(rho in seq(0,1,.1)){
  print(corSim(rho))
}



```

