---
title: 'advanced matrix indexing'
author: "Adam Dede"
date: "2024-03-19"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```
## more indexing tricks 
```{r more matrix indexing tricks}
z = matrix(c(1,2,3,4,5,6), nrow = 2, byrow = T)
#the same indexing tricks used on vectors
#work on matrices
z[,2:3]
z[,-2]


```
## using the dim function on matrices to help index
```{r dim}

#the dim function is useful for finding the 
#shape of a matrix
dim(z)
z[dim(z)[1],] #the last row
z[,dim(z)[2]] #the last column


```
## matrix indexing understanding check
```{r index challenge}

#given this matrix: 
m <- matrix(c(1,2,3,4,5,6,7,8,9,10), nrow = 2)
#how would I get out the values 3,4,5,6?

#what about 6,8,10? 

#how would indexing change if you had made your matrix with row major indexing?
m <- matrix(c(1,2,3,4,5,6,7,8,9,10), nrow = 2, byrow = T)

```

## arrays indexing challenge
```{r arrays}

a = array(c(1:18), dim = c(2,3,3))

#arrays work similarly to matrices
#can you figure out the index to get out
#the following sets: 

#10, 12

#your code here :)

#13, 15, 14, 16

#your code here :)

#6, 12, 18

#your code here :)
```


