---
title: 'data.frames'
author: "Adam Dede"
date: "2024-03-19"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## data frames are a specialized list of lists

```{r make a data.frame}

#
x <- list(name='adam', age = 35, colGrad = T)
y <- list(name='sara', age = 35, colGrad = T)
z <- list(name='bob' , age = 21, colGrad = F)
allDat = list(x,y,z)

#data frames require each column to have all
#the same data mode
name = c('adam', 'sara', 'bob')
age = c(35, 35, 21)
colGrad = c(T,T,F)
allDat  = data.frame(name,age,colGrad)
allDat2 = list(name = name, age = age, 
               colGrad = colGrad)
mode(allDat)
str(allDat)
attributes(allDat)
class(allDat)

```
## indexing works more similarly to a matrix than a list
```{r data.frame indexing}

allDat[2,]
allDat[,2]


```
## this allows rbind and cbind functions to work like they did for matrices!
```{r add rows or columns to a data.frame}

x <- rbind(allDat, list('ann', 32, T))
y <- rbind(allDat, c('ann', 32, T))
#what if anything is different about x and y? 


#or whole columns
z <- cbind(allDat, 
           data.frame('workExp'=c(3,5,8)))
w <- cbind(allDat, c(3,5,8))
names(w)[4] <- 'workExp'
#what if anything is different about z and w? 


```

## list-like indexing is still available though! 
```{r list style indexing}

allDat[[1]][3]
allDat$name[3]
allDat[['name']][3]

#you can also use a variable to access a column by name
varName = 'name'
allDat[[varName]]

```


## data frames are the most common way of storing data in R
```{r reading in a csv}

#data sets in R
covidDat <- read.csv('R:\\MSS\\Johnson_Lab\\dtf8829\\GitHub\\MasterStatsUsingR\\data\\owid-covid-data.csv')

#let's just look at the US
covDatUSA <- covidDat %>% 
  filter(iso_code == 'USA' ) 

covDatUSA2 <- covidDat[covidDat$iso_code == 'USA',]

head(covDatUSA)

covDatUSA <- covDatUSA[,!is.na(covDatUSA[3,])]

```
## tibbles are a type of data frame used in the tidyverse

```{r tibbles}

covDatUSA <- as.tibble(covDatUSA)
covDatUSA
names(covDatUSA)

minSet <-covDatUSA %>% 
  .[c('date', 'new_cases')]

#the biggest functional difference between
#tibbles and data frames is subsetting functions
#in the tidyverse. We'll get into this later!

```
