---
title: 'for loops'
author: "Adam Dede"
date: "2024-03-19"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## let's say you want to do a calculation for multiple inputs

```{r changing inputs}

x = c(1,1,2,4,1,2,3,2,1,1,1,2,34,4,1)
y = c(2,3,1,1,2,4,5,1,1,1,2,3,1,1,1,1,2,3,1,1,4,2,1,1,1)
#what are the indices of two 1s in a row? 

runs <- NULL
for(ii in 1:(length(x)-1)){
  if(all(x[ii:(ii+1)] == 1)){
    runs <- c(runs, ii)
  }
}


runsy <- NULL
for(ii in 1:(length(y)-1)){
  if(all(y[ii:(ii+1)] == 1)){
    runsy <- c(runsy, ii)
  }
}


```
## repeating code is slow, hard to read, and error prone, use a function! 
```{r writing a function}

helloWorld <- function(){
  print("hello world!")
}


findRuns <- function(x){
  runs <- NULL
  for(ii in 1:(length(x)-1)){
    if(all(x[ii:(ii+1)] == 1)){
      runs <- c(runs, ii)
    }
  }
  return(runs)
}

findRuns(x)
findRuns(y)


```

## make your functions flexible! 
```{r soft coding}

#let's say we want to find indices of runs of arbitrary length k
#so far, we've worked with k = 2

findRuns <- function(x, k = 2){
  runs <- NULL
  for(ii in 1:(length(x)-(k-1))){
    if(all(x[ii:(ii+(k-1))] == 1)){
      runs <- c(runs, ii)
    }
  }
  return(runs)
}
findRuns(x,3)
findRuns(y,3)

```

## can you write a function to simulate covid cases? 
```{r breaking out of the loop}

covidDat <- read.csv('C:\\Users\\Adam\\Documents\\GitHub\\
                     MasterStatsUsingR\data\\owid-covid-data.csv')
covUSA <- covidDat %>% filter(iso_code == 'USA')

covUSA$growthRate = NA
L = length(covUSA$growthRate)
covUSA$growthRate[2:L] = covUSA$total_cases[2:L] / covUSA$total_cases[1:L-1]

plot(as.Date(covUSA$date), covUSA$growthRate)

#let's make a function that simulates total cases across days
#the function will take as input the following: 
#growth = multiplicative growth rate: casesToday * r = cases tomorrow
#time = number of time steps to run the simulation 
#startVal = how many cases are observed on day 1

caseSim <- function(growth, time=365, startVal = 1){
  output = rep(NA, time)
  output[1] = startVal
  for(ii in 2:time){
    output[ii] = output[ii-1]*growth
  }
  return(output)
  
}

plot(as.Date(covUSA$date), covUSA$total_cases)
plot(as.Date(covUSA$date), caseSim(1.027, length(covUSA$growthRate)))

plot(as.Date(covUSA$date), log(covUSA$total_cases, base = 10))
plot(as.Date(covUSA$date), log(caseSim(1.027, length(covUSA$growthRate)), base = 10) )

#can you change the way this function is written 
#so that the growth rate can be either a single number or variable over time? 

caseSim2 <- function(growth, time=365, startVal = 1){
  if(length(growth)==1){
    growth = rep(growth, time)
  }
  output = rep(NA, time)
  output[1] = startVal
  for(ii in 2:time){
    output[ii] = output[ii-1]*growth[ii]
  }
  return(output)
  
}

plot(as.Date(covUSA$date), 
     caseSim2(covUSA$growthRate, 
              length(covUSA$growthRate), 
              covUSA$total_cases[1]))

plot(as.Date(covUSA$date), covUSA$total_cases)



```
