---
title: 'data.frames'
author: "Adam Dede"
date: "2024-03-19"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## if statements offer flexible control of computation based on a condition

```{r if intro}
x <- 3
if(x==2){
  print('x is 2')
}

```
## key logical operators in R
```{r logic ops}
#the key to using if statements is making your conditions using logic operators

if(x==2){
  print('x is 2')
}

if(x!=2){
  print('x is not 2')
}

if(x>2){
  print('x is greater than 2')
}

if(x>=2){
  print('x is greater than or equal to 2')
}

if(x<2){
  print('x is less than 2')
}

if(x<=2){
  print('x is less than or equal to 2')
}

```
## What to do if your condition is FALSE? 
```{r else statements}
x <- 3
if(x==2){
  print('x is 2')
}else{
  x = 2
}

#you can sequentially test multiple conditions 
x<- 23
if(x==2){
  print('x is 2')
}else if(x>2){
  print('x is greater than 2')
}else if(x>=2){
  print('x is greater than or equal to 2')
}else if(x<2){
  print('x is less than 2')
}else if(x<=2){
  print('x is less than or equal to 2')
}else{
  print('failed all tests')
}




```
## R sometimes has strange logical outputs! 
```{r NAs are weird}
x<- 'hi'
if(x==2){
  print('x is 2')
}else if(x>2){
  print('x is greater than 2')
}else if(x>=2){
  print('x is greater than or equal to 2')
}else if(x<2){
  print('x is less than 2')
}else if(x<=2){
  print('x is less than or equal to 2')
}else{
  print('failed all tests')
}



```

## we can also test for data mode 
```{r more condition possibilities}

x<- 'hi'
if(is.numeric(x)){
  if(x==2){
    print('x is 2')
  }else if(x>2){
    print('x is greater than 2')
  }else if(x>=2){
    print('x is greater than or equal to 2')
  }else if(x<2){
    print('x is less than 2')
  }else if(x<=2){
    print('x is less than or equal to 2')
  }else{
    print('failed all tests')
  }
} else{
  print('this is not a number!')
}

```

## multiple conditions can be tested at once with & | operators
```{r combining conditions in one statement}

x<- 'hi'
if(is.numeric(x) & x>2){
    print('x is greater than 2')
}

x<- Inf

if(is.na(x) | is.infinite(x)){
  print('value error')
} else{
  print('value is good!')
}


```

## if statements can be applied to whole vectors
```{r vectorized if}
x = c(2,1,3,4,2,5,6,2,1,3,5,1,2)

y <- ifelse(x==2, T, F)

#actually the output arguments here can be vectors as well! 
y <- ifelse(x==2, 1:length(x), NA)
y[!is.na(y)]

#can you write three lines of code that result in printing out two vectors: 
#first vector is the indices of the number 1
#second vector is the indices of all other numbers
y <- ifelse(x==1, 1:length(x), -(1:length(x)))
y[y>0]
y[y<0]*-1
            


```
