---
Title: 'power scratch'
Section: 'Power'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'


library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
# library(pracma)
# library(kableExtra)

```

## simulation for heights 

```{r height sim}
df <- data.frame('men' = dnorm(seq(55,80,.1), 70, 3), 
                 'women' = dnorm(seq(55,80,.1), 65, 3), 
                 'height' = seq(55,80,.1))

df <- pivot_longer(df, cols = c('men', 'women'),
                   values_to = 'density',
                   names_to = 'sex')

df %>% ggplot(aes(x = height, y = density, color = sex)) + 
  geom_line(linewidth = 3) + myTheme + brightCol

W95 = qnorm(.95, 65, 3)

df %>% ggplot(aes(x = height, y = density, color = sex)) + 
  geom_line(linewidth = 3) + myTheme + brightCol + 
   geom_ribbon(data = subset(filter(df, sex == 'men'), 
                            height > W95), 
              aes(y = density, x = height, ymax = density), 
              ymin = 0,  fill = "purple", alpha = .5,
              show.legend = FALSE) + 
  geom_vline(xintercept = W95, color = 'red', linetype = 'dashed', linwidth = 2)


```

## simulation for heights with n = 2

```{r n2}

all_sd = 3 / sqrt(2)

df <- data.frame('men' = dnorm(seq(55,80,.1), 70, all_sd), 
                 'women' = dnorm(seq(55,80,.1), 65, all_sd), 
                 'height' = seq(55,80,.1))

df <- pivot_longer(df, cols = c('men', 'women'),
                   values_to = 'density',
                   names_to = 'sex')

df %>% ggplot(aes(x = height, y = density, color = sex)) + 
  geom_line(linewidth = 3) + myTheme + brightCol

W95 = qnorm(.95, 65, all_sd)

df %>% ggplot(aes(x = height, y = density, color = sex)) + 
  geom_line(linewidth = 3) + myTheme + brightCol + 
   geom_ribbon(data = subset(filter(df, sex == 'men'), 
                            height > W95), 
              aes(y = density, x = height, ymax = density), 
              ymin = 0,  fill = "purple", alpha = .5,
              show.legend = FALSE) + 
  geom_vline(xintercept = W95, color = 'red', linetype = 'dashed', linwidth = 2)

1-pnorm(W95, 70, all_sd)


```

## Example 1: hypothetical heights 

```{r varying sample size}

targetd = c(.2, .3, .4,.5, .6)
F_mean = 65
all_sd = 3
M_mean = 65 + targetd * all_sd
alln = seq(1,100,1)



#how tall is a sample mean of women in the 95th percentile? 
W95 = qnorm(.95, F_mean, all_sd / sqrt(alln))


#what is the probability that a random sample of men will be taller than W95? 
df = data.frame(power = rep(0, length(alln)*length(targetd)),
                n = rep(alln, length(targetd)), 
                d = rep(0, length(alln)*length(targetd)))
for(ii in 1:length(targetd)){
  df$power[((ii-1)*length(alln)+1):
             (ii*length(alln))] = 1-pnorm(W95, M_mean[ii], 
                                       all_sd / sqrt(alln))
  df$n[((ii-1)*length(alln)+1):
         (ii*length(alln))] = alln
  df$d[((ii-1)*length(alln)+1):
         (ii*length(alln))] = targetd[ii]
}
df$d = as.factor(df$d)

df %>% ggplot(aes(x = n, y = power, color = d)) + 
  geom_line(linewidth = 2) + 
  myTheme + brightCol + 
  geom_hline(yintercept = .8, color = 'red', linewidth = 1, linetype = 'dashed')



```
