---
Title: 'Power When n Varies'
Section: 'Power'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'


library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
# library(pracma)
# library(kableExtra)

```

## Example 1: hypothetical heights 

```{r varying sample size}

M_mean = 70
F_mean = 65
all_sd = 3
alln = seq(1,10,1)

#What is the probability that a random sample of men will be 
#taller than 95% of women samples?

#how tall is a sample mean of women in the 95th percentile? 
W95 = qnorm(.95, F_mean, all_sd / sqrt(alln))


#what is the probability that a random sample of men will be taller than W95? 
power = 1-pnorm(W95, M_mean, all_sd / sqrt(alln))

df = data.frame(power = power, 
                n = alln)

df %>% ggplot(aes(x = n, y = power)) + 
  geom_line(linewidth = 2, color = 'green') + 
  myTheme


#what sample size is needed to get 80% power? 
print(df)

```




