---
Title: 'Marketing Data'
Section: 'AB-testing'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(BSDA)
library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)
library(kableExtra)

```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(paste0(gitHubPath, 'data\\WA_Marketing-Campaign.csv'))
df$Promotion = as.factor(df$Promotion)

df<- df %>% group_by(LocationID) %>%
  summarize(SalesInThousands = mean(SalesInThousands),
    across(everything(), ~ first(.), .names = "{.col}"))

df %>% ggplot(aes(y = SalesInThousands, color = Promotion)) + 
    geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())


```

## t-test code, update it to include cohen's d calculation 

```{r t}

pooled_sd <- function(x1, x2) {
  n1 <- length(x1)
  n2 <- length(x2)
  s1 <- sd(x1)
  s2 <- sd(x2)
  
  sqrt(((n1 - 1) * s1^2 + (n2 - 1) * s2^2) / (n1 + n2 - 2))
}

alphaAdjusted = .05/3

getSummary <- function(df, idx1, idx2, alphaAdjusted){
  results = data.frame(test = 'a')
  out = t.test(df$SalesInThousands[df$Promotion == idx1], 
         df$SalesInThousands[df$Promotion == idx2])
  results$test = paste0('promo', idx1, '_v_promo', idx2)
  results$pval = out$p.value
  results$n1 = sum(df$Promotion == idx1)
  results$n2 = sum(df$Promotion == idx2)
  results$mean1 = round(out$estimate[1])
  results$mean2 = round(out$estimate[2])
  results$pooledSD = pooled_sd(df$SalesInThousands[df$Promotion == idx1],
                                  df$SalesInThousands[df$Promotion == idx2])
  results$sigDif = out$p.value < alphaAdjusted
  #add on for d
  results$meanDif = results$mean1 - results$mean2
  results$d = results$meanDif / results$pooledSD
  
  #add on power calculation
  
  critDif = qnorm(1-(alphaAdjusted/2), 0, 
                  results$pooledSD / sqrt(results$n1+results$n2))


#what is the probability that a mean dif will be 
#  greater than critical given a small effect size? 
  
  results$powerSmall = 1-pnorm(critDif, .2*results$pooledSD, 
                results$pooledSD / sqrt(results$n1+results$n2))
  
  results$powerMed = 1-pnorm(critDif, .4*results$pooledSD, 
                results$pooledSD / sqrt(results$n1+results$n2))


  return(results)
}

results = rbind(getSummary(df, 1, 2, alphaAdjusted), 
                getSummary(df, 1, 3, alphaAdjusted),
                getSummary(df, 2, 3, alphaAdjusted)) 



results %>% 
  kbl(align = 'c', digits = 4) %>% 
  kable_classic(full_width = F, 
                font_size = 20)


```

