---
Title: 'ANOVA vs. t-test'
Section: 'One-way ANOVA'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## Set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))


```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(paste0(gitHubPath, 'data\\WA_Marketing-Campaign.csv'))
df$Promotion <- as.factor(df$Promotion)

#average over weeks within store
df<- df %>% group_by(LocationID) %>%
  summarize(SalesInThousands = mean(SalesInThousands),
    across(everything(), ~ first(.), .names = "{.col}"))

```

## Compare ANOVA to t-test results for promotion 1 vs. 2

```{r anova t}

dfCut = df %>% filter(Promotion != 3)

sumA = anova(lm(SalesInThousands ~ Promotion, data = dfCut))

sumT = t.test(dfCut$SalesInThousands[dfCut$Promotion==1], 
       dfCut$SalesInThousands[dfCut$Promotion==2], var.equal = T)

cat('the difference between promotion 1 and 2 yields a t-value of: ',
    round(sumT$statistic, 2), ' \nThis value squared is: ',
    round(sumT$statistic^2, 2), ' \nThe F-value is: ',
    round(sumA$`F value`[1],2))


```


