---
Title: 'Residual Check'
Section: 'One-way ANOVA'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## Set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")

library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))


```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(file.path(gitHubPath, 'data', 
                         'WA_Marketing-Campaign.csv'))
df$Promotion <- as.factor(df$Promotion)

#average over weeks within store
df<- df %>% group_by(LocationID) %>%
  summarize(SalesInThousands = mean(SalesInThousands),
    across(everything(), ~ first(.)))
```

## check assumption that the residuals are normally distributed 

```{r qqplot}

test = lm(SalesInThousands ~ Promotion, data = df)
df$residuals = test$residuals
qVals = seq(.01, 1, .01)


qqVals = data.frame('empirical' = ,
                      'norm'    = ,
                      'qVals'     = )
  
  
  ggplot(qqVals, aes(x = , y = , color = )) + 
    geom_point(size = 3) + 
    geom_abline(slope = 1, intercept = 0)
  
  df$dummy = as.factor(1)
  ggplot(df, aes(x = , fill = dummy))+
    geom_histogram() + brightFil + myTheme + 
  theme(legend.position = 'none')


```

