---
Title: 'One-way ANOVA'
Section: 'One-way ANOVA'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## Set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(BSDA)
library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)
library(lme4)
library(kableExtra)

```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(paste0(gitHubPath, 'data\\WA_Marketing-Campaign.csv'))
df$Promotion <- as.factor(df$Promotion)
```

## But wait! sample size seems too high! REPEAT FROM AB TESTING UNIT 

```{r sample size}

length(unique(df$LocationID))

names(df)

# df %>% ggplot(aes(x = week, y = SalesInThousands, 
#                   group = LocationID, color = LocationID)) + 
#   geom_line(alpha = .5) + 
#   myTheme +
#   scale_color_gradient2(low = "green", mid = "white", high = "magenta",
#                         midpoint = 500)

#is there much variability week to week? 
# df %>% group_by(week) %>% summarize(weeklyMean = mean(SalesInThousands),
#                                     se = sd(SalesInThousands)/sqrt(n()))%>%
#   ggplot(aes(x = week, y = weeklyMean, group = 1)) +
#   geom_line(linewidth = 3, color = 'green') +            # Linegraph
#   geom_point(size = 3, color = 'green') +                # Points for means
#   geom_errorbar(aes(ymin = weeklyMean - se,   # Lower bound of error
#                     ymax = weeklyMean + se),  # Upper bound of error
#                 width = 0.2, color = 'green') +          # Width of error bars
#   myTheme

#view the plot of sales by promotion before averaging across weeks: 
# df %>% ggplot(aes(y = SalesInThousands, color = Promotion)) + 
#     geom_boxplot(linewidth = 2)+ 
#   myTheme + brightCol + brightFil+
#         theme(axis.text.x = element_blank())

df<- df %>% group_by(LocationID) %>%
  summarize(SalesInThousands = mean(SalesInThousands),
    across(everything(), ~ first(.), .names = "{.col}"))

#After averaging over weeks, variability is lower: 
df %>% ggplot(aes(y = SalesInThousands, color = Promotion)) + 
    geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())



```

## Do an ANOVA by hand to test for a difference between promotions

```{r anova}
# Step 1: Do sales vary with different promotions? 
# Step 2: Null: Sales are the same across promotions
#         Alternative: Sales differ across promotions

# Step 3: Degrees of freedom and F critical value
k = length(unique(df$Promotion))  # number of groups
dfbetween = k - 1
dfwithin = nrow(df) - k
Fcrit = qf(.95, df1 = dfbetween, df2 = dfwithin)

# Step 4: Calculate F ratio for the ANOVA
GM = mean(df$SalesInThousands)

# SSbetween: sum(ni * (group mean - grand mean)^2)
SSbetween = 0
for(p in unique(df$Promotion)){
  tmp = df %>% filter(Promotion == p)
  SSbetween = SSbetween + 
    nrow(tmp) * (mean(tmp$SalesInThousands) - GM)^2
}
MSbetween = SSbetween / dfbetween

# SSwithin: sum((x - group mean)^2)
SSwithin = 0
for(p in unique(df$Promotion)){
  tmp = df %>% filter(Promotion == p)
  SSwithin = SSwithin + sum((tmp$SalesInThousands - mean(tmp$SalesInThousands))^2)
}
MSwithin = SSwithin / dfwithin

# F ratio
Fratio = MSbetween / MSwithin

# Step 5: Compare to F critical
# Step 6: Interpretation
if(Fratio > Fcrit){
  cat("The observed F ratio of", round(Fratio, 2),
      "is greater than F critical of", round(Fcrit, 2),
      ".\nStores with different promotions differ in sales.\n")
} else {
  cat("The observed F ratio of", round(Fratio, 2),
      "is NOT greater than F critical of", round(Fcrit, 2),
      ".\nNo evidence stores with different promotions differ in sales.\n")
}

# Built-in comparison
anova(lm(SalesInThousands ~ Promotion, data = df))



```


