---
title: 'Modified z-score outliers'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```
## human EEG data 

```{r EEG}
#load in the restingEEG dataset. 
#Key variable name: pow_delta_O
EEGdat = read.csv(file.path(gitHubPath, 'data',
                            'restingEEG.csv'))

EEGdat$dummy = as.factor(1) 

#plot the overall histogram 
ggplot(EEGdat, aes(x = pow_delta_O, 
                   color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')

#this is the range of data that we worked with in the previous project: 
ggplot(EEGdat, aes(x = pow_delta_O, 
                   color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0,250,1)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')


```

## modified z score calculation  

```{r modified z score}

#now calculate the modified z score 
#using the median absolute deviation
medianVal = 
madVal = 
EEGdat$modZ = 

#how many observations are outliers now? 


#replot it
EEGdat %>% filter(%>%
  ggplot(aes(x = pow_delta_O, 
             color = dummy, fill = dummy)) + 
    geom_histogram() + 
    myTheme + brightFil + brightCol + 
    theme(legend.position = 'none')

#does this seem like the right method of outlier detection for these data? 

```

## modified z score compared to the normal way 

```{r compare z distributions}

EEGdat$normZ = 
zscores = select(


#plot the two types of z-score against each other to see how they relate
ggplot(zscores, aes(x = norm, y = mod)) + 
  geom_point() + 
  ylim(c(-2, 30)) + 
  xlim(c(-.0252, -.022))

#plot again but this time with different colors for the z-score types: 
zscores$idx = 
zscoresLong <- pivot_longer(zscores, cols = -c(idx), 
                            names_to = 'type', 
                            values_to = 'z')

ggplot(zscoresLong, aes(x = idx, y = z, color = type)) + 
  geom_point(size = 2) + myTheme + brightCol + 
  ylim(c(-1, 10))


```

## Repeat the process on the country garbage dataset?

```{r country garbage}

#import the country garbage data set and visualize the totalPop variable: 
wasteDat = read.csv(file.path(gitHubPath, 'data', 
                              'plasticWaste.csv'))

#first plot the histogram of country total populations 
wasteDat$dummy = as.factor(1)
wasteDat %>% ggplot(aes(x = totalPop, 
                        color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')

#calculate the z scores normal and modified 
wasteDat$normZ = 
wasteDat$modZ = 

#What proportion of the data are being called outliers with each method?

#plot the histogram with the outliers removed 
wasteDat %>% filter( %>%
ggplot(aes(x = , color = dummy, fill = dummy)) +
  geom_histogram()+ 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')


wasteDat %>% filter( %>%
ggplot(aes(x = , color = dummy, fill = dummy)) +
  geom_histogram()+ 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')

#what countries are being called outliers? Does this seem like the right method?

# let's do some plotting to look at the two types of z-score
zscores = select(


#plot the two types of z-score against each other to see how they relate
ggplot(zscores, aes(x = normZ, y = modZ)) + 
  geom_point() 

#plot again but this time with different colors for the z-score types: 
zscores$idx = 
zscoresLong <- pivot_longer(zscores, cols = -c(idx), 
                            names_to = 'type', 
                            values_to = 'z')

ggplot(zscoresLong, aes(x = idx, y = z, color = type)) + 
  geom_point(size = 2) + myTheme + brightCol + 
  ylim(c(-1,10))

```

## How would this look if the data were more normal? 

```{r human memory}

memDat = read.csv(file.path(gitHubPath, 'data',
                              'MemoryData.csv'))

#first plot the histogram of country total populations 
memDat$dummy = as.factor(1)
memDat %>% ggplot(aes(x = TargALL_UVSD_d, 
                      color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')

#calculate the z scores normal and modified 
memDat$normZ = 
  
memDat$modZ = 

#What proportion of the data are being called outliers with each method?


#plot the histogram with the outliers removed 
memDat %>% filter( %>% 
ggplot(aes(x = , 
           color = dummy, fill = dummy)) +
  geom_histogram()+ 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')

memDat %>% filter( %>% 
ggplot(aes(x = , 
           color = dummy, fill = dummy)) +
  geom_histogram()+ 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')

# let's do some plotting to look at the two types of z-score
zscores = select(

#plot the two types of z-score against each other to see how they relate
ggplot(zscores, aes(x = normZ, y = modZ)) + 
  geom_point()  

#plot again but this time with different colors for the z-score types: 
zscores$idx = 
zscoresLong <- pivot_longer(zscores, cols = -c(idx), 
                            names_to = 'type', 
                            values_to = 'z')
ggplot(zscoresLong, aes(x = idx, y = z, color = type)) + 
  geom_point(size = 2) + myTheme + brightCol


```
