---
title: 'Normalize one Variable by Another'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## Which country produces the most mismanaged waste? 

```{r country garbage}

#import the country garbage data set: 
wasteDat = read.csv(file.path(gitHubPath, 'data', 
                              'plasticWaste.csv'))

#first plot the histogram of country total mismanaged waste
wasteDat$dummy = as.factor(1)


wasteDat %>% ggplot(aes(x = , 
                        color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')


wasteDat %>% ggplot(aes(, 
                        color = dummy, fill = dummy)) + 
  geom_ + 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')

#divide the total waste by the total population 
wasteDat %>% ggplot(aes(x =   , 
                        color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')


```

## normalize delta power by the total power across all frequencies

```{r relative power}

#we've been working with delta power in the O (occipital) region

#what other frequencies are there? 

EEGdat = read.csv(file.path(gitHubPath, 'data', 
                            'restingEEG.csv'))

EEGdat$dummy = as.factor(1) 

#which variables are from the Occipital region
vars = names(EEGdat)
vars = 

EEGdat$normPow = 

ggplot(EEGdat, aes(x = normPow, 
                   color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')


```
