---
title: 'super extreme outliers'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```
## human EEG data 

```{r EEG}
#load in the restingEEG dataset.
#Key variable name: pow_delta_O
EEGdat = read.csv(file.path(gitHubPath, 'data',
                            'restingEEG.csv'))

EEGdat$dummy = as.factor(1) 

#plot the overall histogram 
ggplot(EEGdat, aes(x = pow_delta_O, 
                   color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')

ggplot(EEGdat, aes(x = pow_delta_O, 
                   color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0,250,.5)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')


```

## How many values are there really at different orders of magnitude? 

```{r super extreme values}

ordersOfMag = data.frame('value' = 
                           , 
                         'count' = rep(0, 8))

delPow = EEGdat$pow_delta_O
for(ii in 1:7){
  ordersOfMag$count[ii] = 
  
}



```
## how big of an impact does just one extreme value have 

```{r single value example}
#what are the mean and SD with the full dataset?
mean(delPow)
sd(delPow)

#what are they when we just remove that one extreme point? 
mean(delPow[-  ])
sd(delPow[-  ])



```

## trimming data before calculating z-score based outliers

```{r zscores of the middle 98}

#let's calculate the z-scores based on only the middle 98% of the data
limVals = quantile(

midMean = 

midSD = 

midZ = (delPow - midMean) / midSD
allZ = (delPow - mean(delPow)) / sd(delPow)

zcompare = data.frame(midZ = midZ, allZ = allZ)

ggplot(zcompare, aes(x = midZ, y = allZ)) + 
  geom_point()


#what proportion of the data would this method eliminate: 


#What is the cutoff value associated with this z value? 




```
## replot without the extreme values 

```{r outlier removal}




ggplot(  , aes(x = pow_delta_O, 
                                 color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')




```