---
title: 'Transform and Z score'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```
## human EEG data 

```{r EEG}
#load in the restingEEG dataset. 
#Key variable name: pow_delta_O
EEGdat = read.csv(file.path(gitHubPath, 'data',
                            'restingEEG.csv'))

EEGdat$dummy = as.factor(1) 

#plot the overall histogram 
ggplot(EEGdat, aes(x = pow_delta_O, 
                   color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol +
  theme(legend.position = 'none')


ggplot(EEGdat, aes(x = , 
                   color = dummy, fill = dummy)) + 
  geom_histogram(bins = 50) + 
  myTheme + brightFil + brightCol +
  theme(legend.position = 'none')




```

## z score calculation  

```{r z score}

#now calculate the z-score on the log transformed data
z = 

#how many observations are outliers now? 


#replot it
ggplot(, aes(x = pow_delta_O, 
             color = dummy, fill = dummy)) + 
  geom_histogram(bins = 100) + 
  myTheme + brightFil + brightCol +
  theme(legend.position = 'none')

#does this seem like the right method of outlier detection for these data? 

```


