---
title: 'z-score Outliers'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## example with human memory data

```{r hum mem}

# identify outliers by visualizing where the +-3 z-score limits are: 
memDat = read.csv(file.path(gitHubPath, 'data',
                                  'MemoryData.csv'))

#add +-3 z score lines to the plot
M = mean(memDat$TargALL_UVSD_d)
S = sd(memDat$TargALL_UVSD_d)

memDat$dummy = as.factor(1)
memDat %>% ggplot(aes(x = TargALL_UVSD_d, 
                      color = dummy, fill = dummy)) + 
  geom_histogram() +  
  geom_vline(xintercept = c(M-3*S, M+3*S), color = 'magenta') + 
  myTheme + brightCol + brightFil + theme(legend.position = 'none')

```

## how do stats change when outliers are removed? 

```{r remove outliers}

#plot the mean and +- 1 SD in the full versus the outlier removed data
memDat$outlier = memDat$TargALL_UVSD_d < -3*S+M | 
                  memDat$TargALL_UVSD_d > 3*S+M
MO =mean(memDat$TargALL_UVSD_d[!memDat$outlier])
SO = sd(memDat$TargALL_UVSD_d[!memDat$outlier])

memDat %>% ggplot(aes(x = TargALL_UVSD_d, 
                      color = outlier, fill = outlier)) + 
  geom_histogram() + 
  geom_vline(xintercept = c(M-S, M+S), color = 'magenta') +
  geom_vline(xintercept = c(MO-SO, MO+SO), color = 'green') +
  myTheme + brightCol + brightFil + theme(legend.position = 'none')

```

## removing outliers affects the z-scores of every single data points! 

```{r remove outliers all effects}

#what is the probability of observing someone 
#with memory equal to the best 
#participant both with and without outliers in the calculation? 
1 - pnorm(max(memDat$TargALL_UVSD_d), M, S)
1 - pnorm(max(memDat$TargALL_UVSD_d), MO, SO)


#plot all z-scores both before and after getting rid of outliers
memDat$z_ALL = (memDat$TargALL_UVSD_d - M) / S
memDat$z_no_outliers = (memDat$TargALL_UVSD_d - MO) / SO

memDat$idx = c(1:length(memDat$z_ALL))

plotDat = memDat %>% select(z_ALL, z_no_outliers, idx) %>%
  pivot_longer(cols = c(z_ALL, z_no_outliers), 
               names_to = 'ZType', 
               values_to = 'z')

plotDat %>% ggplot(aes(x = idx, y = z, color = ZType)) + 
  geom_point() + myTheme + brightCol  


```

## human EEG data 

```{r EEG}

EEGdat = read.csv(file.path(gitHubPath, 'data',
                                'restingEEG.csv'))

EEGdat$dummy = as.factor(1) 

#plot the overall histogram 
ggplot(EEGdat, aes(x = pow_delta_O, 
                   color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')

#this is the range of data that we worked with in the previous project: 
ggplot(EEGdat, aes(x = pow_delta_O, 
                   color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0,250,5)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')


```

## try z-score based outlier removal to take out z>3

```{r z greater than 3 remove}

M = mean(EEGdat$pow_delta_O)
S = sd(EEGdat$pow_delta_O)
 



EEGdat %>% ggplot(aes(x = pow_delta_O, 
                      color = dummy, fill = dummy)) + 
  geom_histogram() + 
  geom_vline(xintercept = c(M+3*S, M-3*S), color = 'magenta') + 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none')

#how many values are actually outliers? 
#What will the graph look like without them?

sum(EEGdat$pow_delta_O > M+3*S)


#how does the plot look with these outliers removed? 
EEGdat %>% filter(pow_delta_O < M+3*S) %>%
      ggplot(
       aes(x = pow_delta_O, 
           color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none')

#What proportion of the data are less than the mean? 
sum(EEGdat$pow_delta_O < M) / length(EEGdat$X)
M


```


