---
Title: 'abScratch'
Section: 'AB-testing'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(BSDA)
library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)
library(lme4)

```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(paste0(gitHubPath, 'data\\WA_Marketing-Campaign.csv'))
df$Promotion = as.factor(df$Promotion)


df %>% ggplot(aes(y = SalesInThousands, color = Promotion)) + 
    geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())


df %>% ggplot(aes(y = SalesInThousands, color = MarketSize)) + 
  geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())

df %>% ggplot(aes(x = AgeOfStore, y = SalesInThousands, color = MarketSize)) + 
  geom_jitter() + 
  myTheme + brightCol + brightFil

df %>% ggplot(aes(x = week, y = SalesInThousands, 
                  group = LocationID, color = LocationID)) + 
  geom_line(alpha = .5) + 
  myTheme +
  scale_color_gradient2(low = "green", mid = "white", high = "magenta",
                        midpoint = 500)

df<- df %>% group_by(LocationID) %>%
  summarize(SalesInThousands = mean(SalesInThousands),
    across(everything(), ~ first(.), .names = "{.col}"))


```

## do a matched-sample t-test

```{r t test}
# install.packages("MatchIt")
library(MatchIt)


promoCompare <- function(df, targPromos){
  #compare 1 v. 2
  dfTmp = df %>% filter(Promotion == targPromos[1] | 
                        Promotion == targPromos[2])
  
  out = t.test(dfTmp$SalesInThousands[dfTmp$Promotion == targPromos[1]],
         dfTmp$SalesInThousands[dfTmp$Promotion == targPromos[2]], 
         paired = F)
  print(out)
  
  print(dfTmp %>% ggplot(aes(y = SalesInThousands, 
                             color = Promotion))+
          geom_boxplot() +
          myTheme + brightCol + brightFil)
  
  print(dfTmp %>% ggplot(aes(x = MarketSize, 
                             color = Promotion, fill = Promotion))+
          geom_bar(position = "dodge") +
          myTheme + brightCol + brightFil) 
  # Use nearest neighbor matching on the chosen variable
  matching_result <- matchit(Promotion ~ MarketSize, 
                             data = dfTmp, method = "nearest")
  
  # Get the matched data
  matched_data <- match.data(matching_result)
  
  matched_data = matched_data %>% arrange(subclass, Promotion)
 
  # matched_pairs <- matched_data %>% 
  #   group_by(subclass) %>% 
  #   ungroup()
  
  
    # filter(sum(Promotion == targPromos[1]) == 1 & 
    #        sum(Promotion == targPromos[2]) == 1) 
  
  p1 = matched_data %>% filter(Promotion == targPromos[1])
  p2 = matched_data %>% filter(Promotion == targPromos[2])
  
  #which campaign gets more impressions? 
  print(t.test(p1$SalesInThousands, p2$SalesInThousands, paired = T))
  # matched_pairs = matched_pairs %>% arrange(Promotion)
  
  print(matched_data %>% group_by(subclass) %>% 
          summarize(difVal = SalesInThousands[1] - SalesInThousands[2]) %>% 
          ggplot(aes(x = difVal))+
          geom_histogram(color = '#20CDF2', fill = '#20CDF2') +
          myTheme)
  
}

df %>% arrange(runif(length(df$LocationID))) -> df
promoCompare(df, c(1,3))
promoCompare(df, c(1,2)) 

promoCompare(df, c(2,3))



```

# mixed effects model 

```{r}

df <- read.csv(paste0(gitHubPath, 'data\\WA_Marketing-Campaign.csv'))
df$Promotion = as.factor(df$Promotion)

df <- df %>%
  mutate(
    MarketID = as.factor(MarketID),
    LocationID = as.factor(LocationID),
    week = as.factor(week)
  )

test.lm <- lmer(
  SalesInThousands ~ Promotion * MarketSize  + 
      (1 | LocationID), 
  data = df
)   

summary(test.lm)


```
