---
Title: 'Cohens D'
Section: 'AB-testing'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(BSDA)
library(pracma)
library(kableExtra)

```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(file.path(gitHubPath, 'data', 
                         'WA_Marketing-Campaign.csv'))
df$Promotion = as.factor(df$Promotion)

df <- df %>%
  group_by(LocationID) %>%
  summarize(
    SalesInThousands = mean(SalesInThousands),
    across(-SalesInThousands, ~ first(.))
  )

df %>% ggplot(aes(y = SalesInThousands, 
                  color = Promotion)) + 
    geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())


```

## t-test code, update it to include cohen's d calculation 

```{r t}

# d = (mean1 - mean2) / pooledSD

pooled_sd <- function(x1, x2) {
 
}

alphaAdjusted = .05/3


getSummary <- function(){
  

  return(results)
}

results = 



results %>% 
  kbl(align = 'c', digits = 4) %>% 
  kable_classic(full_width = F, 
                font_size = 20)


```

