---
Title: 'Marketing Data'
Section: 'AB-testing'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(BSDA)
library(pracma)
library(kableExtra)

```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(file.path(gitHubPath, 'data', 
                         'WA_Marketing-Campaign.csv'))
df$Promotion = as.factor(df$Promotion)


df %>% ggplot(aes(y = SalesInThousands, 
                  color = Promotion)) + 
    geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())


```

## do t-tests to compare 

```{r t tests}

alphaAdjusted = .05/3

results = data.frame('test' = c('0','0','0'), 
                     'pval' = c(0,0,0),
                     'n1' = c(0,0,0),
                     'n2' = c(0,0,0),
                     'mean1' = c(0,0,0),
                     'mean2' = c(0,0,0),
                     'sigDif'= c(0,0,0))

out = t.test(df$SalesInThousands[df$Promotion == 1], 
       df$SalesInThousands[df$Promotion == 2])
results$test[1] = paste0('promo', 1, '_v_promo', 2)
results$pval[1] = out$p.value
results$n1[1] = sum(df$Promotion == 1)
results$n2[1] = sum(df$Promotion == 2)
results$mean1[1] = round(out$estimate[1])
results$mean2[1] = round(out$estimate[2])
results$sigDif[1] = out$p.value < alphaAdjusted

out = t.test(df$SalesInThousands[df$Promotion == 1], 
       df$SalesInThousands[df$Promotion == 3])
results$test[2] = paste0('promo', 1, '_v_promo', 3)
results$pval[2] = out$p.value
results$n1[2] = sum(df$Promotion == 1)
results$n2[2] = sum(df$Promotion == 3)
results$mean1[2] = round(out$estimate[1])
results$mean2[2] = round(out$estimate[2])
results$sigDif[2] = out$p.value < alphaAdjusted

out = t.test(df$SalesInThousands[df$Promotion == 2], 
       df$SalesInThousands[df$Promotion == 3])
results$test[3] = paste0('promo', 2, '_v_promo', 3)
results$pval[3] = out$p.value
results$n1[3] = sum(df$Promotion == 2)
results$n2[3] = sum(df$Promotion == 3)
results$mean1[3] = round(out$estimate[1])
results$mean2[3] = round(out$estimate[2])
results$sigDif[3] = out$p.value < alphaAdjusted

results %>% 
  kbl(align = 'c', digits = 4) %>% 
  kable_classic(full_width = F, 
                font_size = 20)

```

## but wait! sample size seems too high

```{r sample size}

length(unique(df$LocationID))

names(df)

df %>% ggplot(aes(x = week, y = SalesInThousands, 
                  group = LocationID, 
                  color = LocationID)) + 
  geom_line(alpha = .5) + 
  myTheme +
  scale_color_gradient2(low = "green", mid = "white", high = "magenta",
                        midpoint = 500)

#is there much variability week to week? 
df %>% group_by(week) %>% 
  summarize(weeklyMean = mean(SalesInThousands),
            se = sd(SalesInThousands)/sqrt(n())) %>%
  ggplot(aes(x = week, y = weeklyMean, group = 1)) +
  geom_line(linewidth = 3, color = 'green') +    
  geom_point(size = 3, color = 'green') + 
  geom_errorbar(aes(ymin = weeklyMean - se,   
                    ymax = weeklyMean + se),  
                width = 0.2, color = 'green') +       
  myTheme

df <- df %>%
  group_by(LocationID) %>%
  summarize(
    SalesInThousands = mean(SalesInThousands),
    across(-SalesInThousands, ~ first(.))
  )

#After averaging over weeks, variability is lower: 
df %>% ggplot(aes(y = SalesInThousands, color = Promotion)) + 
    geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())

```

## Let's rerun the t-tests with the right sample size now

```{r rerun t}

alphaAdjusted = .05/3
oldRes = results 
results = data.frame('test' = c('0','0','0'), 
                     'pval' = c(0,0,0),
                     'n1' = c(0,0,0),
                     'n2' = c(0,0,0),
                     'mean1' = c(0,0,0),
                     'mean2' = c(0,0,0),
                     'sigDif'= c(0,0,0))

out = t.test(df$SalesInThousands[df$Promotion == 1], 
       df$SalesInThousands[df$Promotion == 2])
results$test[1] = paste0('promo', 1, '_v_promo', 2)
results$pval[1] = out$p.value
results$n1[1] = sum(df$Promotion == 1)
results$n2[1] = sum(df$Promotion == 2)
results$mean1[1] = mean(df$SalesInThousands[df$Promotion == 1])
results$mean2[1] = mean(df$SalesInThousands[df$Promotion == 2])
results$sigDif[1] = out$p.value < alphaAdjusted

out = t.test(df$SalesInThousands[df$Promotion == 1], 
       df$SalesInThousands[df$Promotion == 3])
results$test[2] = paste0('promo', 1, '_v_promo', 3)
results$pval[2] = out$p.value
results$n1[2] = sum(df$Promotion == 1)
results$n2[2] = sum(df$Promotion == 3)
results$mean1[2] = mean(df$SalesInThousands[df$Promotion == 1])
results$mean2[2] = mean(df$SalesInThousands[df$Promotion == 3])
results$sigDif[2] = out$p.value < alphaAdjusted

out = t.test(df$SalesInThousands[df$Promotion == 2], 
       df$SalesInThousands[df$Promotion == 3])
results$test[3] = paste0('promo', 2, '_v_promo', 3)
results$pval[3] = out$p.value
results$n1[3] = sum(df$Promotion == 2)
results$n2[3] = sum(df$Promotion == 3)
results$mean1[3] = mean(df$SalesInThousands[df$Promotion == 2])
results$mean2[3] = mean(df$SalesInThousands[df$Promotion == 3])
results$sigDif[3] = out$p.value < alphaAdjusted

results %>% 
  kbl(align = 'c', digits = 4) %>% 
  kable_classic(full_width = F, 
                font_size = 20)
oldRes %>% 
  kbl(align = 'c', digits = 4) %>% 
  kable_classic(full_width = F, 
                font_size = 20)

```

