---
title: 't-test on split continuous data'
Section: 'AB testing'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human EEG data 

```{r EEG}

#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                    'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)


ggplot(df, aes(x = age, y = log(pow_delta_O,10), 
               color = dummy)) + 
  geom_point(size = 2) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') +
  xlab("age (months)")

#filter to children less tahn 8 and replot: 
df <- df %>% filter(  )




```

## human EEG babies vs. kids

```{r t test split}

df$babyChild = 


t.test()

```

