---
title: 'Adding Extra Predictors'
Section: 'Multiple Linear Regression'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output: 
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))


```

## human EEG data 

```{r EEG}

df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

df = df[df$group == 'CON' | df$group == "AD",]

df <- df %>% filter(age<(18*12))

reduced.lm = lm(log(pow_delta_O,10) ~ age , data = df)
full.lm = lm(log(pow_delta_O,10) ~ age+sex+group , data = df)



```

## Doing a significance test on a regression

```{r sig test}

#Step 1: is delta power predicted BETTER be a combination of
#age, sex, and autism diagnosis than by just age alone? 

#step 2: Null: Extra predictors DO NOT improve the model fit beyond age alone
#        Alternative: Extra predictors DO improve the model fit beyond age alone 

#step 3: let's skip calculating a critical F value
#instead, we'll calculate a p-value from our observed F value
dfreg = 3 - 1 #number of predictors in FULL - predictors in REDUCED  
dferr = length(df$age) - dfreg - 1 #this is always the same! 


#step 4: calculate F ratio for the regression

#SS values 
SSerr = sum(full.lm$residuals^2)
yMean = reduced.lm$fitted.values #we use the reduced model as the comparison
#how much variability is there around the reduced model? 
SStotal = sum((log(df$pow_delta_O,10) - yMean)^2) 
SStotal2 = sum(reduced.lm$residuals^2) #equivalent! 
SSreg = SStotal - SSerr

#get F ratio: 
Fratio = (SSreg / dfreg) / (SSerr / dferr)

#step 5: compare F ratio observed to critical value
#INSTEAD, let's calculate the p-value now: 
pVal = 1 - pf(Fratio, dfreg, dferr)
#AND step 6: provide interpretation to answer the question
if(pVal < .05){
  cat("F-statistic:", round(Fratio,2), 
               "on", dfreg, 'and', dferr, 'DF, p-value: ', round(pVal, 5),
            '\n the full model is better than the reduced.')
} else{
  cat("F-statistic:", round(Fratio,2), 
               "on", dfreg, 'and', dferr, 'DF, p-value: ', round(pVal, 5),
               ".\n No evidence that full model is better than reduced")
}

#compare to builtin output: 
anova(reduced.lm, full.lm)



```




