---
Title: 'Paired Sample Signed Rank Test'
Section: 'Wilcoxon Test'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human memory data

```{r data}
df = read.csv(file.path(gitHubPath, 'data',
                      'MemoryData.csv'))

df <- df %>% filter(TargALL_UVSD_d >=0)

df$memDif = df$L1cor_UVSD_d - df$L5_UVSD_d

#first plot the histogram of country total populations 
df$dummy = as.factor(1)
df %>% ggplot(aes(x = memDif, color = dummy, fill = dummy)) + 
  geom_histogram(bins = 10) + 
  xlab('L5 better     Mem Dif      L1 better') +
  myTheme + brightCol + brightFil + theme(legend.position = 'none')

```

## do a Wilcoxon Test

```{r test}

wilcox.test(df$memDif, mu = 0)

t.test(df$memDif, mu = 0)


```

