---
title: 'Wilcoxon Random Samples'
Section: 'Wilcoxon Test'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human EEG data 

```{r EEG}

#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                  'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

df <- df %>% filter(age<(8*12))

df$babyChild = df$age<50
df$babyChild[df$babyChild] = 'baby'
df$babyChild[df$babyChild=='FALSE'] = 'child'



```

## random sub sample of size 10 per group

```{r random}
numTests = 1000
pvals = data.frame(tlog = rep(0,numTests),
           t = rep(0,numTests),
           wil = rep(0,numTests))
for(ii in 1:numTests){
  
  
 
  pvals$tlog[ii] = 
  pvals$t[ii] = 
  pvals$wil[ii] = 
}

print(paste(sum(pvals$tlog<.05), 'of ', 
            numTests,' for Log Transformed t-test'))
print(paste(sum(pvals$t<.05), 'of ', 
            numTests,' for t-tests on raw data'))
print(paste(sum(pvals$wil<.05), 'of ', 
            numTests,' for Wilcoxon Test'))


```


