---
title: 'Simulating Multiple Tests'
Section: 'Multiple Comparisons'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## simulating multiple null tests 

```{r null}

numTests = 1000
results = data.frame(pval = rep(0,numTests),
                     sig = rep(0, numTests),
                     alphaAdjust = .05/numTests,
                     sigCor = rep(0,numTests))
groupVar = c(rep(1,50), rep(2,50))

for(ii in 1:numTests){
 values = rnorm(100)
  x = values[groupVar == 1]
  y = values[groupVar == 2] 
  

  out = t.test(x, y)
  results$pval[ii] = out$p.value
  results$sig[ii] = as.numeric(out$p.value < .05)
  results$sigCor[ii] = as.numeric(out$p.value <
                                    results$alphaAdjust[1])
}

results <- results %>% arrange(pval)

head(results)
results$dummy = as.factor(1)

results %>% ggplot(aes(x=pval, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0,  .1/(numTests/10),.01/(numTests))) + 
  geom_vline(xintercept = results$alphaAdjust[1], color = 'red') + 
  myTheme + brightCol + brightFil + theme(legend.position = 'none')

sum(results$sigCor) / numTests

```
## simulating  real differences

```{r diff}

realDifVal = 1
numTests = 1000

results = data.frame(pval = rep(0,numTests),
                     sig = rep(0, numTests),
                     alphaAdjust = .05/numTests,
                     sigCor = rep(0,numTests))
groupVar = c(rep(1,50), rep(2,50))

for(ii in 1:numTests){
 values = rnorm(100)
  x = values[groupVar == 1]
  y = values[groupVar == 2] 
  
  #add a real difference:
  y = y + rnorm(length(y), mean = realDifVal)
  out = t.test(x, y)
  results$pval[ii] = out$p.value
  results$sig[ii] = as.numeric(out$p.value < .05)
  results$sigCor[ii] = as.numeric(out$p.value < results$alphaAdjust[1])
}

results <- results %>% arrange(pval)

head(results)
results$dummy = as.factor(1)

results %>% ggplot(aes(x=pval, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(0,  .1/(numTests/10),.01/(numTests))) + 
  geom_vline(xintercept = results$alphaAdjust[1], color = 'red') + 
  myTheme + brightCol + brightFil + theme(legend.position = 'none')

sum(results$sigCor) / numTests

```

