---
title: 'multiple comparison scratch'
Section: 'Multiple Comparisons'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human EEG data 

```{r EEG}

df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))

# df$dummy = as.factor(1) 
# df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)
df = df[df$age > 216 & df$age < 600,]
powidx = which(grepl('pow', names(df)))
results = data.frame('pval' = rep(0,length(powidx)),
                     'sig'  = rep(0,length(powidx)))
for(ii in 1:length(powidx)){
  x = df[df$sex == "F",powidx[ii]]
  y = df[df$sex == "M",powidx[ii]]
  x = x[0<x & x<250]
  y = y[0<y & y<250]
    out = t.test(x, y)
    results$pval[ii] = out$p.value
    results$sig[ii] = as.numeric(out$p.value < .05)
    results$sigCor[ii] = as.numeric(out$p.value < (.05/length(powidx)))
    results$varName[ii] = names(df)[powidx[ii]]
    results$n = length(x) + length(y)
}

results$dummy = as.factor(1)
results %>% ggplot(aes(x=pval, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(0,.5,.05)) + 
  myTheme + brightCol + brightFil + 
  theme(legend.position = 'none') + 
  geom_vline(xintercept = .05, color = 'red', linewidth = 2, linetype = 'dashed')


```

## simulating multiple small real differences with a function

```{r functionSim}

simulator <- function(numTests, realDifVal){
    results = data.frame(pval = rep(0,numTests),
                       sig = rep(0, numTests),
                       alphaAdjust = .05/numTests,
                       sigCor = rep(0,numTests))
  groupVar = c(rep(1,50), rep(2,50))
  
  for(ii in 1:numTests){
   values = rnorm(100)
    x = values[groupVar == 1]
    y = values[groupVar == 2] 
    
    #add a real difference:
    y = y + rnorm(length(y), mean = realDifVal)
    out = t.test(x, y)
    results$pval[ii] = out$p.value
    results$sig[ii] = as.numeric(out$p.value < .05)
    results$sigCor[ii] = as.numeric(out$p.value < results$alphaAdjust[1])
  }
  return(results)
}

difVals = c(.2,.4,.6,.8,1)
numTestVals = c(10,100,1000,10000)
sigByNum = data.frame(numTests = rep(0,length(numTestVals)*length(difVals)), 
                      difVal = rep(0,length(numTestVals)*length(difVals)),
                      sigProp = rep(0,length(numTestVals)*length(difVals)))
alli = 1
for(kk in 1:length(difVals)){
  print(paste('kk is: ', kk))
  difVal = difVals[kk]
  for(jj in 1:length(numTestVals)){
    print(jj)
    numTests = numTestVals[jj]
    if(numTests < 1000){
      allRes = data.frame(propSig = rep(0, 1000/numTests))
      for(ii in 1:(1000/numTests)){
        curRes = simulator(numTests, difVal)
        allRes$propSig[ii] = sum(curRes$sigCor) / numTests
      }
      sigByNum$sigProp[alli] = mean(allRes$propSig)
      sigByNum$numTests[alli] = numTests
      sigByNum$realDif[alli] = difVal
      alli = alli + 1
    } else {
      curRes = simulator(numTests, difVal)
      sigByNum$sigProp[alli] = sum(curRes$sigCor) / numTests
      sigByNum$numTests[alli] = numTests
      sigByNum$realDif[alli] = difVal
      alli = alli + 1
    }
  }
}
sigByNum$realDif <- as.factor(sigByNum$realDif) 
sigByNum %>% ggplot(aes(x = log(numTests,10), 
                        y = sigProp, 
                        color = realDif)) + 
  geom_line(linewidth = 2) + myTheme + brightCol



```