---
title: 'Constant Value Transformations'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## sp 500 daily change 

```{r sp 500}

df = read.csv(file.path(gitHubPath, 'data', 
                        'SP500HistoricalData.csv'))
names(df)[6] <- 'Change'

df$Change = unlist(lapply(df$Change, function(x)
              as.numeric(strsplit(x, '%')[[1]])))

df$dummy = as.factor(1) 

ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)') 

```

##let's think about how we can compare this distribution to a log normal distribution more critically 

```{r compare to log}
df$logChange = log(df$Change)

ggplot(df, aes(x = Change, y = logChange, color = dummy)) + 
  geom_point(size = 2) + myTheme + brightCol + 
  theme(legend.position = 'non')

#but we know there are negative change values. 
#The stock market doesn't ALWAYS go up! 

df$logChange = log(df$Change + abs(min(df$Change))+.01)

constantValAdjustment = abs(min(df$Change))+.01

ggplot(df, aes(x = Change + constantValAdjustment, 
               y = logChange, color = dummy)) + 
  geom_point(size = 2) + myTheme + brightCol + 
  theme(legend.position = 'none')

ggplot(df, aes(x = logChange, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-3, 1, .1)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (adjusted and log transformed)') 


```

## can we compare these log data to a normal distribution! 

```{r descriptives for sp500}

x <- df$logChange
analyticDists <- data.frame('norm' = dnorm(x, mean(x), sd(x)),
                            'logChange' = x)


analyticDists <- analyticDists %>% pivot_longer(
                       cols = names(analyticDists)[-2], 
                       values_to = 'density', 
                       names_to = 'dist')



df$dist = "empirical data"
df %>% ggplot(aes(x = logChange, color = dist)) + 
  geom_freqpoly(aes(y = after_stat(density)), 
                linewidth = 2, bins = 50) +
  geom_line(data = analyticDists, 
            aes(x = logChange , 
                y = density), linewidth = 2) + 
  brightCol +  myTheme + 
  ggtitle("adjusted log change SP 500 compare to normal") 



```

## Interpreting constant value transformed data 

```{r interpretation}


#how can we think about the density values we have relative to raw SP500 changes?
#reverse the math! 
analyticDists$rawChange = exp(analyticDists$logChange) -
                            constantValAdjustment


df %>% ggplot(aes(x = Change, color = dist)) + 
  geom_freqpoly(aes(y = ..density..), linewidth = 2, bins = 50) +
  geom_line(data = analyticDists, aes(x = rawChange, y = density), linewidth = 2) + 
  brightCol +  myTheme + 
  ggtitle("SP 500 Change compare to log normal") 


```

