---
title: 'Log plus Z'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human EEG data 

```{r EEG}
#load in the restingEEG dataset. 
#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                              'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

ggplot(df, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

```

## TRANSFORM 1: What do EEG power values look like after log transform? 

```{r take log transform}

df$logPow_delta_O = log(df$pow_delta_O)

ggplot(df, aes(x = logPow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')+ 
  xlab('EEG delta power (log transformed)') 

#looks much more normal! 


```


## TRANSFORM 2: stack a z-transform on top of a log transform

```{r add z transform}

M = 
S = 

df$log_z_Pow_delta_O = 


ggplot(df, aes(x =  , 
               color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('EEG delta power (log and z transformed)') 


```

## using the z values to say things about the raw values

```{r say things about raw based on z}

#for this code block, z-score always refers to 
# z-score in the log transformed data

#what proportion of people have EEG delta power greater than 50? 

z = 

#what EEG delta power values correspond to z scores of +- 1? 


print(paste0("Z = -1 corresponds to a raw power value of: ", 
                  ,
             ", and Z = +1 corresponds to a raw power value of: ", 
                      ))

#What proportion of the raw data fall between these +-1 z-score? 
midPercent = sum(df$pow_delta_O>exp(-1*S+M) & 
                  df$pow_delta_O<exp(1*S+M)  ) / length(df$X) 

print(paste0(round(midPercent,2), 
             " of raw power values are between +- 1 z-score in the ",
             "log-transformed distribution"))



```

## how would the +- 1 z-score proportion change if we hadn't log transformed?

```{r no log}

M =
S = 

midPercent = 

print(paste0(round(midPercent,2), 
             " of raw power values are between +- 1 z-score in the ",
             "raw distribution"))



```


