---
title: 'Log Transformation'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human EEG data 

```{r EEG}
#load in the restingEEG dataset. 
#Key variable name: pow_delta_O
df = read.csv(file.path(gitHubPath, 'data',
                          'restingEEG.csv'))

df$dummy = as.factor(1) 
df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)

ggplot(df, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

```

## TRANSFORM 1: What do EEG power values look like after log transform? 

```{r take log transform}

df$logPow_delta_O = 

ggplot(df, aes(x =       , 
               color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

#looks much more normal! 
#let's look at how these log transformed data compare to a normal distribution

```

## comparing log transformed data to normal distribution 

```{r compare normal}


x <- df$logPow_delta_O
analyticDists <- data.frame('norm' = dnorm(x,), 
                            'xVal' = x)


analyticDists <- analyticDists %>% 
              pivot_longer(



df$dist = "empirical data"
df %>% ggplot(

```



## TRANSFORM 2: what if we transform back into raw data values? 

```{r exp back}

df %>% ggplot(


```

## Perfect equivalence between normal and log normal values

```{r equivalence}

## log normal values found relative to the raw data: 
lnormVals_raw = dlnorm(

## normal values found relative to the log transformed data: 

normVals_log = dnorm(

plot(normVals_log, lnormVals_raw)


all.equal(normVals_log, lnormVals_raw)

```

