---
title: 'Min Max Scaling'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```

## human memory data 

```{r hum mem}

df = read.csv(file.path(gitHubPath, 'data', 
                              'MemoryData.csv'))

df <- df %>% filter(TargALL_UVSD_d >=0)

df$dummy = as.factor(1)
df %>% ggplot(aes(x = TargALL_UVSD_d, color = dummy, fill = dummy)) + 
  geom_histogram(bins = 10) + 
  myTheme + brightCol + brightFil + theme(legend.position = 'none')

```

## Apply min max scaling to the data

```{r minMax scale}

minVal = min(df$TargALL_UVSD_d)
maxVal = max(df$TargALL_UVSD_d)

df$scaledMemory = (df$TargALL_UVSD_d - minVal) / 
                  (maxVal - minVal)


df %>% ggplot(aes(x = scaledMemory, color = dummy, fill = dummy)) + 
  geom_histogram(bins = 10) + 
  myTheme + brightCol + brightFil + theme(legend.position = 'none') + 
  xlab('scaled memory') 

#can you figure out how to set custom breaks in the histograms to 
#make the shapes identical? 

```

