---
title: 'Model V Empirical'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```



## sp 500 daily change 

```{r sp 500}

df = read.csv(file.path(gitHubPath, 'data', 
                        'SP500HistoricalData.csv'))
names(df)[6] <- 'Change'

df$Change = unlist(lapply(df$Change, 
                function(x) as.numeric(strsplit(x, '%')[[1]])))

df$dummy = as.factor(1) 

ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)') 

```

## using z-scores what is the probability of a 1% gain

```{r model gain of 1}

M = mean(df$Change)
S = sd(df$Change)

1 - pnorm(1, M, S)


```

## Using the empirical data what is the probability of a gain of 1%

```{r empirical gain of 1}

sum(df$Change > 1) / length(df$Change)


```

