---
title: 'normalizations'
author: "Adam Dede"
date: "2024-07-23"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)


gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'
library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(pracma)

```
## human EEG data 

```{r EEG}

df = read.csv(paste0(gitHubPath, 'data\\restingEEG.csv'))

df <- df %>% filter(pow_delta_O < 250, pow_delta_O > 0)
df$dummy = as.factor(1) 

ggplot(df, aes(x = pow_delta_O, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-20, 250, .5)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

df$meanCentered = df$pow_delta_O - mean(df$pow_delta_O)
ggplot(df, aes(x = meanCentered, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-20, 250, .5)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')

df$zscore = df$meanCentered / sd(df$pow_delta_O)
ggplot(df, aes(x = zscore, color = dummy, fill = dummy)) + 
  geom_histogram(breaks = seq(-2, 10, .5/ sd(df$pow_delta_O))) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')


df <- df %>% filter(pow_delta_O>0)

ggplot(df, aes(x = log(pow_delta_O,10), color = dummy, fill = dummy)) + 
  geom_histogram() + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none')


df$pow_delta_O = log(df$pow_delta_O, 10)

EEGsum <- df %>% summarize(setName = 'deltaPow', 
                               meanVal = mean(pow_delta_O), 
                               medianVal = median(pow_delta_O), 
                               modeVal = Mode(round(pow_delta_O)), 
                               sdVal = sd(pow_delta_O), 
                               logMean = mean(log(pow_delta_O+ abs(min(pow_delta_O))+.001)),
                               logSD = sd(log(pow_delta_O+ abs(min(pow_delta_O))+.001)), 
                               offSet = abs(min(pow_delta_O))+.001, 
                               q25 = quantile(pow_delta_O, .25), 
                               q75 = quantile(pow_delta_O, .75), 
                               MADval = sum(abs(pow_delta_O - meanVal)) / 
                                          (n()-1)) 



```

## make it into a function for ease of use

```{r functionitize}

plotAgainstDists <- function(df, varOfInterest, empiricalBreaks, sumVals, title){

  L = length(empiricalBreaks)
  empiricalDensity = rep(0, L)
  
  for(ii in 1: L){
    empiricalDensity[ii] = sum(df[[varOfInterest]] < empiricalBreaks[ii])
  }
  empiricalDensity = (empiricalDensity[-1] - empiricalDensity[-L]) / 
                     (empiricalBreaks[-1] - empiricalBreaks[-L]) 
  empiricalBreaks = (empiricalBreaks[-1] + empiricalBreaks[-L]) / 2
  
  analyticDists <- data.frame('empiricalData' =empiricalDensity,
                              'norm' = dnorm(empiricalBreaks, 
                                             mean = sumVals$meanVal, 
                                             sd = sumVals$sdVal),
                              'poisson' = dpois(round(empiricalBreaks), 
                                             lambda = sumVals$meanVal), 
                              'logNorm' = dlnorm(empiricalBreaks+sumVals$offSet, 
                                                 meanlog = sumVals$logMean, 
                                                 sdlog = sumVals$logSD), 
                              'unif' = dunif(empiricalBreaks, 
                                             min = min(df[[varOfInterest]]), 
                                             max = max(df[[varOfInterest]])), 
                              'xVal' = empiricalBreaks)
  
  
  analyticDists <- analyticDists %>% pivot_longer(cols = names(analyticDists)[-6], 
                                                 values_to = 'density', 
                                                 names_to = 'dist')
  
  # analyticDists$xVal[analyticDists$dist == 'logNorm'] <- 
  #             analyticDists$xVal[analyticDists$dist == 'logNorm'] - sumVals$offSet
  
  analyticDists <- analyticDists %>% group_by(dist) %>%
                  mutate(density = density / sum(density))
  
  analyticDists %>% ggplot(aes(x = xVal, y = density, color = dist)) + 
    geom_line(linewidth = 2) + brightCol + myTheme + 
    ggtitle(title)

}
plotAgainstDists(df, "pow_delta_O", quantile(df$pow_delta_O, seq(.01,1,.025)), EEGsum, "title")


```
## normal distribution properties! 

```{r norm dist}

df = data.frame('simulatedData' = rnorm(10000000))
df$dummy = as.factor(1)
df %>% ggplot(aes(x = simulatedData, color = dummy)) + 
  geom_freqpoly(bins = 100, linewidth = 2) + 
  geom_vline(xintercept = c(0, 1, -1, 2, -2), color = 'magenta') +
  xlim(c(-5, 5)) + scale_x_continuous(breaks = c(-2, -1, 0, 1, 2)) + 
  myTheme + brightCol + theme(legend.position = 'none', 
                              axis.text.y = element_blank())

```

## log scaling covid data example

``` {r log cov}

covidDat <- read.csv('C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\data\\owid-covid-data.csv')
covUSA <- covidDat %>% filter(iso_code == 'USA')

covUSA$date = as.Date(covUSA$date)

covUSA %>% ggplot(aes(x = date, y = total_cases, group = iso_code, color = iso_code)) + 
  geom_line(linewidth = 2) + 
  scale_x_date(date_breaks = "6 month", date_labels = "%m/%y") +
  myTheme + brightCol + 
  theme(legend.position = 'none')

covUSA %>% ggplot(aes(x = date, y = log(total_cases, base = 10), group = iso_code, color = iso_code)) + 
  geom_line(linewidth = 2) + myTheme + brightCol + 
  scale_x_date(date_breaks = "6 month", date_labels = "%m/%y")+
  theme(legend.position = 'none')

# growth = data.frame(growthRate = 
#                       covUSA$total_cases[-1]  / 
#                       covUSA$total_cases[-length(covUSA$total_cases)])
# 
# growth %>% ggplot(aes(x = growthRate))+
#   geom_freqpoly(breaks = seq(1, 1.5, .001))


```

## example simulation of log normal data transformed to normal

```{r simulation example}

simDat = data.frame('lnormDat' = rlnorm(20000))
simDat$LOGlnormDat = log(simDat$lnormDat)
simDat <- simDat %>% pivot_longer(cols = names(simDat), 
                                  names_to = 'dataType', 
                                  values_to = 'values')

simDat %>% ggplot(aes(x = values, color = dataType)) + 
  geom_freqpoly(linewidth = 2, breaks = seq(-5,10,.1)) + myTheme + brightCol



```

## log normal is multiplicative

```{r simulation example 2}

simDat = data.frame('baseVals' = rnorm(20000, 100, 10),
                    'changeVals' = rnorm(20000, 2, .5)+1)
simDat$finalVals = simDat$baseVals * simDat$changeVals

simDat <- simDat %>% pivot_longer(cols = names(simDat), 
                                  names_to = 'dataType', 
                                  values_to = 'values')

simDat %>% ggplot(aes(x = values, color = dataType)) + 
  geom_freqpoly(aes(y = ..density..), linewidth = 2) + myTheme + brightCol



```
