---
title: 'Z Scores'
Section: 'Scaling and Transformations'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


library(tidyverse) # data manipulation and visualization
source(file.path(gitHubPath, 'courseTheme.R'))
library(pracma)

```



## sp 500 daily change 

```{r sp 500}

df = read.csv(file.path(gitHubPath, 'data', 
                        'SP500HistoricalData.csv'))
names(df)[6] <- 'Change'

df$Change = unlist(lapply(df$Change, 
                function(x) as.numeric(strsplit(x, '%')[[1]])))

df$dummy = as.factor(1) 

ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)') 

```

## sp 500 z-scores

```{r z score sp500}

df$zScore = 


#can you figure out how to do the adjustment in the histogram breaks to make
#the plot look exactly like the previous one? 


ggplot(df, aes(x = zScore, color = dummy, fill = dummy)) +
  geom_histogram(breaks = ) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (z-score)') 


```

## Using the normal distribution to tell how rare a daily % change is

```{r determining probabilities}

#What percentage of the time is the daily change greater than 2%? 



ggplot(df, aes(x = zScore, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq((-2-M)/S, (2-M)/S, .1/S)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  xlab('Daily Change (z-score)') +
  geom_vline(xintercept = , color = 'red')

#what percentage of the time is the daily change positive? 



ggplot(df, aes(x = zScore, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq((-2-M)/S, (2-M)/S, .1/S)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  xlab('Daily Change (z-score)') +
  geom_vline(xintercept =  , color = 'red')

#what percentage of the time is the z-score greater than 0? 



ggplot(df, aes(x = zScore, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq((-2-M)/S, (2-M)/S, .1/S)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  xlab('Daily Change (z-score)') +
  geom_vline(xintercept =   , color = 'red')

#what percentage of the time is the daily change between -1% and +1%



ggplot(df, aes(x = zScore, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq((-2-M)/S, (2-M)/S, .1/S)) + 
  myTheme + brightFil + brightCol + theme(legend.position = 'none') + 
  xlab('Daily Change (z-score)') +
  geom_vline(xintercept = , color = 'red')


```

## plot particular z-scores onto the raw data distribution

```{r z scores on raw}

#where are the +- 1 z-score boundaries in the raw data? 



ggplot(df, aes(x = Change, color = dummy, fill = dummy)) +
  geom_histogram(breaks = seq(-2, 2, .1)) + 
  myTheme + brightFil + brightCol + 
  theme(legend.position = 'none') + 
  xlab('Daily Change (%)') +
  geom_vline(xintercept =  , color = 'red')

#what percentage of the raw data fall between +- 1 z-score? 



#what percentage of the normal distribution is between +- 1 z-score? 



```

## How rare are the most extreme changes in our dataset? 

```{r rarity of events}

#how rare are the extreme days: 



#In 252 trading days, would you expect to observe such rare events by chance? 
numberLessThanMin = rep(0, 1000)
numberMoreThanMax = rep(0, 1000)
#simulate 1000 years of data: 
for(ii in 1:1000){
  simSP500 = 
    #did the year have extreme values? 
}

print(paste0("In 1000 years we expect ", sum(numberLessThanMin), 
             " years with worse days than the worst day last year"))
print(paste0("In 1000 years we expect ", sum(numberMoreThanMax), 
             " years with better days than the best day last year"))




```
