---
title: 'AdvancedGroupBy'
author: "Adam Dede"
date: "2024-07-21"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
library(lubridate)

```

## grouping data to get counts of a category

```{r email data}

df = read.csv(paste0(gitHubPath, '\\data\\emailTimes.csv'))

df <- df %>% group_by(DayOfWeek, Month, DayOfMonth, Year) %>% 
  summarize(count = n(), .groups = 'drop')


```
## What can we do about days with zero emails? We still want to count these

```{r dealing with zeros}

df = read.csv(paste0(gitHubPath, '\\data\\emailTimes.csv'))
# Step 1: Generate a complete date range 
start_date <- as.Date('2020-06-14')
end_date <- as.Date('2024-07-14')
complete_dates <- seq.Date(start_date, end_date, by = 'day')

# Step 2: Create a data frame with the complete date range 
#         and extract day of the week month, day, and year
calendar_df <- data.frame(
  Date = complete_dates,
  DayOfWeek = weekdays(complete_dates),
  Month = month(complete_dates),
  DayOfMonth = day(complete_dates),
  Year = year(complete_dates)
)

month_abbr <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')

# Create a vector of abbreviated month names to numeric conversion
month_abbr_to_num <- function(month) {
  match(month, month_abbr)
}

# Convert example abbreviated month names to numeric
df$MonthNum <- month_abbr_to_num(df$Month)


df$Date = as.Date(paste(df$Year, df$MonthNum, df$DayOfMonth, sep = '-'))

calendar_df$count = 0 

counts = df %>% group_by(Date) %>%
  summarize(count = n()) 

# Step 3: Merge full set of calendar dates and observed counts
df_full <- calendar_df %>%
  left_join(counts, by = "Date", 
            suffix =c("_remove","")) %>%
  replace_na(list(count = 0)) %>%
  select(which(!grepl("remove", names(.))))



```

