---
title: 'describing real data'
author: "Adam Dede"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(knitr)
library(pracma)

```

## human EEG data 

```{r EEG}
#load in the restingEEG dataset. There are a lot of variables in this dataset
#for this analysis let's just focus on the delta power in the occipital region 
#of the head. 
#Key variable name: pow_delta_O
df = read.csv(paste0(gitHubPath, '\\data\\restingEEG.csv'))


hist(df$pow_delta_O[df$pow_delta_O < 250])
```

## sp 500 daily change 

```{r sp 500}

df = read.csv(paste0(gitHubPath, '\\data\\SP500HistoricalData.csv'))
names(df)
#let's simplify the name of column 6
names(df)[6] <- 'Change'

# Initialize an empty numeric vector to store the cleaned values
cleaned_values <- numeric(length(df$Change))

# Loop through each element in df$Change
for (i in seq_along(df$Change)) {
  # Remove the percent sign and convert to numeric
  cleaned_values[i] <- as.numeric(strsplit(df$Change[i], '%')[[1]])
}

# Assign the cleaned values back to the dataframe
df$Change <- cleaned_values

#the following line does the same thing: 
# df$Change = unlist(lapply(df$Change, function(x) 
#   as.numeric(strsplit(x, '%')[[1]])))

hist(df$Change)

```


