---
title: 'Renaming and Pivoting'
Section: 'Importing Data Into R'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output: 
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## Set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))
library(car)


```

## Import data on Obesity Risk

```{r import}
#data source: https://data.cdc.gov/Chronic-Disease-Indicators/U-S-Chronic-Disease-Indicators/hksd-2xuw/about_data
df = read.csv(paste0(gitHubPath, '\\data\\U.S._Chronic_Disease_Indicators.csv'))

```

## Examine what data are available for later analysis

```{r choose data}
#We want to predict cardiovascular disease

names(df)

unique(df$Topic)

unique(df$Question[df$Topic == "Cardiovascular Disease"])

Qcut = df[grepl("Diseases of the heart", df$Question), ]

unique(Qcut$StratificationCategory1)

#let's take "Diseases of the heart mortality among all people, underlying cause"
#as our outcome that we'd like to predict
#And let's just look at this "Overall" 

#what stuff do we think will be likely to cause or predict or be associated 
#with heart disease mortality? 
unique(df$Topic)
goodVars = c("Diseases of the heart mortality among all people, underlying cause")
unique(df$Question[df$Topic == "Sleep"])
goodVars = c(goodVars, unique(df$Question[df$Topic == "Sleep"])[2])
unique(df$Question[df$Topic == "Mental Health"])
goodVars = c(goodVars, unique(df$Question[df$Topic == "Mental Health"])[c(1,2,3)])
unique(df$Question[df$Topic == "Tobacco"])
goodVars = c(goodVars, unique(df$Question[df$Topic == "Tobacco"])[c(1,7)])
unique(df$Question[df$Topic == "Nutrition, Physical Activity, and Weight Status"])
goodVars = c(goodVars, 
             unique(df$Question[df$Topic == 
           "Nutrition, Physical Activity, and Weight Status"])[c(1,3,6,9)])
unique(df$Question[df$Topic == "Alcohol"])
goodVars = c(goodVars, unique(df$Question[df$Topic == "Alcohol"])[c(2,7)])
unique(df$Question[df$Topic == "Oral Health"])
goodVars = c(goodVars, unique(df$Question[df$Topic == 
                                            "Oral Health"])[c(1,2,6,7)])
unique(df$Question[df$Topic == "Social Determinants of Health"])
goodVars = c(goodVars, 
             unique(df$Question[df$Topic == 
           "Social Determinants of Health"])[c(1,2,3,5,6,8,9,10,11,12)])
unique(df$Question[df$Topic == "Cognitive Health and Caregiving"])
goodVars


```

## Rename the long form questions 

```{r rename}

#long versions of questions
longNames <- goodVars

shortNames = c("cardioDeath", "shortSleep", "depression", "mentalDistress", 
               "badDays", 
               "smoking", "smokeBan", "obesity", "noActivity", "noVeg",
               "noFruit", "BingeDrink", "alcohol", "allTeeth", "noTeeth", 
               "dentist",
               "lostTeeth", "doctor", "noInsure", "unemployment", 
               "poverty", "noInternet", "highSchool", "noFood", "noRent",
               "noSocial", "noTransport")

# Check that lengths match
stopifnot(length(longNames) == length(shortNames))

# Create a named vector: names are long strings, values are short names
name_map <- setNames(shortNames, longNames)

# Add the short version to the df
df <- df %>% filter(Question  %in% longNames) %>%
  mutate(Question_short = name_map[Question])

```

## Cut to just the 'Overall' values and pivot wider

```{r cut pivot}

df <- df %>% filter(StratificationCategory1 == 'Overall')

df <- df %>% select(YearStart, LocationAbbr, LocationDesc, Question, 
              DataValueUnit, DataValueType, DataValue, Question_short) 

unique(df$DataValueType)

df_filtered <- df %>%
  group_by(LocationAbbr, YearStart, Question) %>%
  mutate(has_age_adjusted = any(grepl("Age-adjusted", DataValueType))) %>%
  filter(if (has_age_adjusted[1]) grepl("Age-adjusted", DataValueType) else TRUE) %>%
  ungroup()

test = df_filtered[df_filtered$LocationDesc == "California" & 
                     df_filtered$YearStart== 2022,]
stopifnot(length(unique(test$Question_short)) == length(test$Question_short))

df_wide <- df_filtered %>%
  pivot_wider(
    id_cols = c(YearStart, LocationAbbr, LocationDesc, DataValueType),
    names_from = Question_short,
    values_from = DataValue
  ) 

```

## Simplify by averaging over years

```{r simplify}

df_summary <- df_wide %>%
  group_by(LocationAbbr, LocationDesc) %>%
  summarise(
    across(where(is.numeric), ~mean(.x, na.rm = TRUE)),
    .groups = "drop"
  ) %>% drop_na()

```

## Save for later

```{r save}

write.csv(df_summary, paste0(gitHubPath, '\\data\\cardioData_sum.csv') )

```