---
title: 'central tendency '
author: "Adam Dede"
date: "2024-07-14"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

courseThemePath = 
  "C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\courseTheme.R"

library(tidyverse) # data manipulation and visualization
source(courseThemePath)


```

## simualte data from all four distributions we know

```{r simulate data}

sampSize = 100000

df = data.frame('norm' = rnorm(sampSize, 3, 1),
                'lnorm' = rlnorm(sampSize,log(3), 1), 
                'unif' = runif(sampSize,-2, 8),
                'pois' = rpois(sampSize, lambda = 3))
df <- df %>% pivot_longer(cols = c(names(df)), 
                   values_to = 'observed', 
                   names_to = 'dist')

p <- df %>% filter(dist != 'pois') %>%
  ggplot(aes(x = observed, group = dist, color = dist, fill = dist)) + 
  geom_freqpoly(breaks = seq(-3, 15, .1), linewidth = 3) + 
  myTheme + brightCol + brightFil

print(p) 
```
## calculate the central tendancy measures for the different distributions
``` {r central tendency measures}



# Calculate group means
group_means <- df %>% filter(dist != 'pois') %>%
  group_by(dist) %>%
  summarise(mean_val = mean(observed),
            mode_val = Mode(observed),
            median_val = median(observed)) %>%
  pivot_longer(cols = -all_of(c('dist')), 
               values_to = 'centralTend', 
               names_to = 'type')


# Add vertical lines for group means
p + geom_vline(data = group_means, aes(xintercept = centralTend, 
                                       color = dist,
                                       linetype = type), size = 1) +
   guides(
    linetype = guide_legend(override.aes = list(color = "pink"))) + 
  theme(legend.key.height = unit(1.5, "cm")) +
  facet_grid(dist~.)


```
## can you make a plot for the poisson distribution? 

```{r plotting poisson}



```
