---
Title: 'Doing a two-way ANOVA'
Section: 'Two-Way ANOVA'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'


library(tidyverse) # data manipulation and visualization
source(paste0(gitHubPath, 'courseTheme.R'))


```

## advertising data
#https://www.kaggle.com/datasets/chebotinaa/fast-food-marketing-campaign-ab-test

```{r data}
df <- read.csv(paste0(gitHubPath, 'data\\WA_Marketing-Campaign.csv'))
df$Promotion <- as.factor(df$Promotion)

#average over weeks within store
df<- df %>% group_by(LocationID) %>%
  summarize(SalesInThousands = mean(SalesInThousands),
    across(everything(), ~ first(.), .names = "{.col}"))

df %>% ggplot(aes(y = SalesInThousands, color = Promotion)) + 
    geom_boxplot(linewidth = 2)+ 
  myTheme + brightCol + brightFil+
        theme(axis.text.x = element_blank())+
  facet_grid(.~MarketSize)


```

## Doing a two-way ANOVA

```{r two way}

#step 1: 
#how do sales change with different combinations of market size and promotion?

#step 2: There are now multiple sets of null and alternative hypotheses to test
#is there a main effect of market size? Null: no; Alt: yes
#is there a main effect of promotion? Null: no; Alt: yes
#is there an interaction between factors? Null: no; Alt: yes

#step 3: calcualte the F ratios

GM = mean(df$SalesInThousands)
#calculate all the different sums of squares: 
#initialize at zero 
SSbetMarSize = 0
A = length(unique(df$MarketSize)) #how many levels of market size are there? 
dfbetMarSize = A - 1
marSizeLevels = unique(df$MarketSize)
#loop over market sizes: 
for(ss in 1:A){
  ##SS per group = n*(groupMean - GM)^2
  tmp = df %>% filter(MarketSize == marSizeLevels[ss])
  n = nrow(tmp)
  SSbetMarSize = SSbetMarSize + n*(mean(tmp$SalesInThousands) - GM)^2
}

SSbetProm = 0
B = length(unique(df$Promotion)) #how many levels of market size are there? 
dfbetProm = B - 1
promLevels = unique(df$Promotion)
#loop over market sizes: 
for(pp in 1:B){
  ##SS per group = n*(groupMean - GM)^2
  tmp = df %>% filter(Promotion == promLevels[pp])
  n = nrow(tmp)
  SSbetProm = SSbetProm + n*(mean(tmp$SalesInThousands) - GM)^2
}

#for the interaction and the within SS values, we'll need to nest two loops!
#SSinter = nab*(meanab - meana - meanb + GM)^2
#needs to loop over levels of factor A and B
SSinter = 0
SSwithin = 0
dfinter = (A-1)*(B-1)
dfwithin = nrow(df) - A*B
#loop over market sizes: 
for(ss in 1:A){
  for(pp in 1:B){
    meana = mean(df$SalesInThousands[df$MarketSize == marSizeLevels[ss]])
    meanb = mean(df$SalesInThousands[df$Promotion==promLevels[pp]])
    ##SS per group = n*(groupMean - GM)^2
    tmp = df %>% filter(MarketSize == marSizeLevels[ss],
                        Promotion == promLevels[pp])
    n = nrow(tmp)
    SSinter = SSinter + n*(mean(tmp$SalesInThousands) - 
                                 meana - meanb + GM)^2
    SSwithin = SSwithin + sum((tmp$SalesInThousands - 
                                mean(tmp$SalesInThousands))^2)
  }
}

#convert to mean squared values: 
MSbetMarSize = SSbetMarSize / dfbetMarSize
MSbetProm = SSbetProm / dfbetProm
MSinter = SSinter / dfinter
MSwithin = SSwithin / dfwithin 

#calculate F-ratios: 
FbetMarSize = MSbetMarSize / MSwithin 
FbetProm = MSbetProm / MSwithin 
Finter = MSinter / MSwithin 

#steps 4: get p values: 

pbetMarSize = 1 - pf(FbetMarSize, dfbetMarSize, dfwithin)
pbetProm = 1 - pf(FbetProm, dfbetProm, dfwithin)
pinter = 1 - pf(Finter, dfinter, dfwithin)

#step 5: answer the question with respect to the null and alt hypotheses: 
resPrint <- function(effectName, df, SS, MS, Fval, pval){
  cat(effectName, '; Df: ', df, '; SS: ', round(SS, 1), 
      '; MS: ', round(MS, 1), '; F: ', round(Fval, 3), 
      '; p(>F): ', pval, sep = '')
}

resPrint('Promotion', dfbetProm, SSbetProm, MSbetProm, FbetProm, pbetProm)
resPrint('MarketSize', dfbetMarSize, SSbetMarSize, MSbetMarSize, FbetMarSize, 
         pbetMarSize)
resPrint('Interaction', dfinter, SSinter, MSinter, Finter, pinter)


test = lm(SalesInThousands ~ Promotion * MarketSize, data = df)

anova(test)

#The values are a little different? 

```

## Try a reordered analysis to see if we can replicate R's output

```{r simplify}
test = lm(SalesInThousands ~ MarketSize*Promotion, data = df)

anova(test)
resPrint('MarketSize', dfbetMarSize, SSbetMarSize, MSbetMarSize, FbetMarSize, 
         pbetMarSize)

#ORDER MATTERS! What's happening? 

```
## Look at Sums of Squares Total to get a Clue

```{r SStotal}

test = lm(SalesInThousands ~ MarketSize*Promotion, data = df)

aovTab = anova(test)

SStotal = sum((df$SalesInThousands - GM)^2)
SSsumedTotal = SSbetMarSize+SSbetProm+SSinter+SSwithin
SSANOVATotal = sum(aovTab$`Sum Sq`)

cat(  'SStotal:      ', round(SStotal),
    '\nSSsumedTotal: ', round(SSsumedTotal), 
    '\nSSANOVATotal: ', round(SSANOVATotal))

```


