---
title: 'data.frames'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")



```

## data frames are a specialized list of lists

```{r make a data.frame}
x <- list(name='adam', age = 35, colGrad = T)
y <- list(name='sara', age = 35, colGrad = T)
z <- list(name='bob' , age = 21, colGrad = F)
allDat = list(x,y,z)

name = c('adam', 'sara', 'bob')
age = c(35, 35, 21)
colGrad = c(T, T, F)
allDat2 = data.frame(name, age, colGrad)
allDat3 = list(name = name, age = age, colGrad = colGrad)
mode(allDat2)
mode(allDat3)
str(allDat2)
str(allDat3)
attributes(allDat2)
attributes(allDat3)



```
## indexing works more similarly to a matrix than a list
```{r data.frame indexing}

allDat2[2,]
allDat2[,2]

allDat2$name
allDat2$age



```
## this allows rbind and cbind functions to work like they did for matrices!
```{r add rows or columns to a data.frame}
x <- rbind(allDat2, list('ann', 32, T))
y <- rbind(allDat2, c('ann', 32, T))
str(x)
str(y)

z <- cbind(allDat2, 'workExp' = c(3,5,8))
w <- cbind(allDat2, c(3,5,8))


```

## list-like indexing is still available though! 
```{r list style indexing}
allDat2[[1]][1]
allDat2$age[3]

varName = 'name'
allDat2[[varName]][1]


```


## data frames are the most common way of storing data in R
```{r reading in a csv}
covidDat <- read.csv(file.path(gitHubPath, "data", 
                               "owid-covid-data.csv"))


covDatUSA <- covidDat %>% 
  filter(iso_code == 'USA' ) 

covDatUSA2 <- covidDat[covidDat$iso_code == 'USA',]

head(covDatUSA)

covDatUSA <- covDatUSA[,!is.na(covDatUSA[3,])]


```
## tibbles are a type of data frame used in the tidyverse

```{r tibbles}
covDatUSA <- as_tibble(covDatUSA)
names(covDatUSA)



```
