---
title: 'for loops'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## Doing a calculation for every observation in a set of data

```{r repeating a calculation}
x = c(1,2,3,5)
#can you count the number of odd numbers in this vector? 
oddCount = 0


```
## repeating code is slow, hard to read, and error prone, use a loop! 
```{r the for loop}
oddCount = 0



```

## R lets you make this even simpler by avoiding indexing
```{r direct iteration}
oddCount = 0
#can you count the odd values by looping the values directly? 



```

## what if we don't always want to loop every value? 
```{r breaking out of the loop}
x = c(3,6,1,6,1)
 #can we use a for loop to find the first 1


```
## find runs of 1s with length equal to 2
```{r runs of 1s}
x = c(1,1,2,4,1,2,3,2,1,1,1,2,34,4,1)
#what are the indices of two 1s in a row



```
## simplify with the all function
```{r all any}
x = c(1,1,2,4,1,2,3,2,1,1,1,2,34,4,1)
#what are the indices of two 1s in a row? 



#can you write a for loop that finds 
# indices where consecutive values
# are 1 and 2 OR 2 and 1? 

```
