---
title: 'functions'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


```

## let's say you want to do a calculation for multiple inputs

```{r changing inputs}
x = c(1,1,2,4,1,2,3,2,1,1,1,2,34,4,1)
y = c(2,3,1,1,2,4,5,1,1,1,2,3,1,1,1,1,2,3,1,1,4,2,1,1,1)
#what are the indices of two 1s in a row? 


```
## repeating code is slow, hard to read, and error prone, use a function! 
```{r writing a function}




```

## make your functions flexible! 
```{r soft coding}



```

## can you write a function to simulate covid cases? 
```{r breaking out of the loop}
covidDat <- read.csv(file.path(gitHubPath, "data", 
                               "owid-covid-data.csv"))
covUSA <- covidDat %>% filter(iso_code == 'USA')

covUSA$growthRate = NA
L = length(covUSA$growthRate)
covUSA$growthRate[2:L] = covUSA$total_cases[2:L] / covUSA$total_cases[1:L-1]

plot(as.Date(covUSA$date), covUSA$growthRate)


#Goal: simulate total cases across days
#Inputs: 
#growth = multiplicative growth rate: 
#                   casesToday * growth = cases tomorrow
#time = number of time steps to run the simulation 
#startVal = how many cases are observed on day 1




```
