---
Title: 'Helper Scripts'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## can you write a function to simulate covid cases? 
```{r breaking out of the loop}
covidDat <- read.csv('C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\data\\owid-covid-data.csv')
covUSA <- covidDat %>% filter(iso_code == 'USA')

covUSA$growthRate = NA
L = length(covUSA$growthRate)
covUSA$growthRate[2:L] = covUSA$total_cases[2:L] / covUSA$total_cases[1:L-1]

plot(as.Date(covUSA$date), covUSA$growthRate)


#let's make a function that simulates total cases across days
#the function will take as input the following: 
#growth = multiplicative growth rate: casesToday * growth = cases tomorrow
#time = number of time steps to run the simulation 
#startVal = how many cases are observed on day 1

caseSim <- function(growth, time = 365, startVal = 1){
  output = rep(NA, time)
  output[1] = startVal
  for(ii in 2:time){
    output[ii] = output[ii-1]*growth
  }
  return(output)
  
}

plot(as.Date(covUSA$date), covUSA$total_cases)
plot(as.Date(covUSA$date), caseSim(1.027, length(covUSA$date), 1))

#constant growth might not be right, how about a variable growth rate? 
caseSimVar <- function(growth, time = 365, startVal = 1){
  output = rep(NA, time)
  output[1] = startVal
  for(ii in 2:time){
    output[ii] = output[ii-1]*growth[ii]
  }
  return(output)
  
}

plot(as.Date(covUSA$date), covUSA$total_cases)
plot(as.Date(covUSA$date), caseSimVar(covUSA$growthRate, 
                                      length(covUSA$date), 1))

randOrderGrowth = sample(covUSA$growthRate, length(covUSA$growthRate), 
                         replace = F)
randOrderGrowth[is.na(randOrderGrowth)] <- 1.0
plot(as.Date(covUSA$date), caseSimVar(randOrderGrowth, 
                                      length(covUSA$date), 1))


```
