---
title: 'if statements'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## if statements offer flexible control of computation based on a condition

```{r if intro}
x <- 2
if(x == 2){
  print('x is 2')
}

```
## key logical operators in R
```{r logic ops}

x = 5

if(x == 2){
  print('x is 2')
}

if(x != 2){
  print('x is not 2')
}

if(x > 2){
  print('x is greater than 2')
}

if(x >= 2){
  print('x is greater than or equal to 2')
}

if(x < 2){
  print('x is less than 2')
}

if(x <= 2){
  print('x is less than or equal to 2')
}



```
## What to do if your condition is FALSE? 
```{r else statements}

x<- 3
if (x==2){
  print('x is 2')
} else {
  x = 2
}

x<-T
if(x == 2){
  print('x is 2')
}else if(x > 2){
  print('x is greater than 2')
}else if(x < 2){
  print('x is less than 2')
}else {
  print('unknown')
}




```
## R sometimes has strange logical outputs! 
```{r NAs are weird}
x<- 'hi'
if(x == 2){
  print('x is 2')
}else if(x > 2){
  print('x is greater than 2')
}else if(x < 2){
  print('x is less than 2')
}else {
  print('unknown')
}


```

## we can also test for data mode 
```{r more condition possibilities}
x<- 'hi'
if(is.numeric(x)){
  if(x == 2){
    print('x is 2')
  }else if(x > 2){
    print('x is greater than 2')
  }else if(x < 2){
    print('x is less than 2')
  }else {
    print('unknown')
  }
}else{
  print('this is not a number')
}


```

## multiple conditions can be tested at once with & | operators
```{r combining conditions in one statement}
x<- 'hi'
if(is.numeric(x) & x>2){
  print('x is greater than 2')
}

x <- 5
if(is.na(x) | is.infinite(x)){
  print('value error')
} else {
  x + 3
}


```

## if statements can be applied to whole vectors
```{r vectorized if}
x = c(2,1,3,4,2,5,6,2,1,3,5,1,2)
            
y <- ifelse(x==2, T, F)

y <- ifelse(x==2, 1:length(x), NA)
y[!is.na(y)]

#can you write 3 lines, provide the two vectors of output: 
#vec 1: indices of the number 1
#vec 2: indices of all other number? 

y <- ifelse(x==1, 1:length(x), -(1:length(x)))
y[y>0]
y[y<0]*-1

```
