---
title: 'Lists'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## lists let you combine different data modes

```{r make a list}
x <- list(name = 'adam', age = 35, colGrad = T)
mode(x)
attributes(x)
str(x)
names(x)

```
## lists don't have to have names
```{r nameless list}
xNameless <- list('adam', 35, T)
xNameless[[1]]

x$name

x[['name']]

varName = 'name'

x[[varName]]



```

## we can also add names to an unnamed list
```{r adding names}
xNameless
names(xNameless) <- c('name', 'age', 'colGrad')
xNameless

unname(xNameless)


```

## converting to a vector, but watch out for coercion! 

```{r unlist}
unlist(x)


```
## lists of lists are kind of like what matrices are to vectors
```{r lists of lists}
x <- list(name = 'adam', age = 35, colGrad = T)
y <- list(name = 'sara', age = 30, colGrad = T)
z <- list(name = 'bob', age = 22, colGrad = F)
allDat <- list(x, y, z)

allDat[[3]]$age
allDat[[3]][[2]]
allDat[[3]][['age']]

```

