---
title: 'logs and exponents'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)
gitHubPath <- file.path(path.expand("~"), "GitHub", 
                        "MasterStatsUsingR")


```

## Working with natural exponents has a special builtin function: exp

```{r natural exponents and logs}

#exponentiation or raising the natural number e to the x
#make a sequence of x values to test with
x = seq(from = 0,to = 10, by = .1)
#alternative syntax: 
x = seq(0,10,.1)

#raise e to the x
y = exp(x)



```

## Quick plot to help build intuition 
```{r add scatter plot}

 #plotting can help visual understanding! 
plot(x, y)



```

## taking the log of something is the inverse of exponentiation

```{r log v exponentiation}

#1 = log(x, base = exp(1)) 
#what is x? 

exp(1)
log(2.71, base = exp(1))

#base = exp(1) is default
log(2.71)

#even more concretely, we can be sure that these operations are inverses: 
log(exp(1))
exp(log(10))
log(exp(10))

```

## Let's build intuition for log values using a plot

```{r log x plot}

plot(x, log(x))


```

## Can log(x) and exp(x) values be negative? 

```{r log and exp negatives}
log(-1)
#is there ever a negative result to the exp() function? 
exp(-1)


```
## mini project using logs and real data

```{r COVID data and log scaling}
#we've just seen examples dealing with logs and exponents using base e
#let's look at it with base 10 and with some real data

#question: when during the pandemic was the US experiencing an increasing rate
#of covid spread? 
#data obtained from: https://covid.ourworldindata.org/data/owid-covid-data.csv
#data downloaded on: 17/11/2021

covidDat <- read.csv(file.path(gitHubPath, "data", 
                               "owid-covid-data.csv"))
covUSA <- covidDat %>% filter(iso_code == 'USA')

#make a plot
plot(as.Date(covUSA$date), covUSA$total_cases)


#what happens if we plot it on a logarithmic y axis? 
plot(as.Date(covUSA$date), log(covUSA$total_cases, base = 10))

 
#why in the regular scale does it look like it's changing more towards the end, 
#but in the log scale it looks like it's changing more towards the beginning? 
#remember standard number scale is about the absolute number of cases
#the log scale tells us more about the multiplicative scale or the order of magnitude
#what this tells us is that the multiplicative growth rate in covid cases was much larger early in the pandemic
#let's assess this by asking, what is the multiplicative relationship between
#one day's covid case count and the day before's? 
#use vectorization math like we did before, but now, we want to ask, what's the relationship between each day and the day before?
covUSA$growthRate = NA
L = length(covUSA$growthRate)
covUSA$growthRate[2:L] = covUSA$total_cases[2:L] / 
                         covUSA$total_cases[1:(L-1)]


plot(as.Date(covUSA$date), covUSA$growthRate)




#reminder for thinking about log scale: 
log(1000000, base = 10)
log(1e6, base=10)

#what is 7 on a log base 10 scale? 


#can you generate a similar set of plots for the running death count? 
#can you generate a similar set of plots for another country? 


```


