---
title: 'Using R like a calculator'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "https://www.udemy.com/course/statsr_ad" 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

# Using R like a calculator
```{r doing basic math operations}

#addition
1 + 1

#subtraction
5-2

#multiplication
3*5

#division
7/2

#modulo
7%%2


```

# Use R to write out algebraic formulas and solve


```{r algebra example}
#basic algebra
#can you solve 15 = x*3 ? 
x = # try out an answer

#test your answer
x*3


```

# Exponents are a bit more complex but easy to use in R

```{r exponents}
#exponents
3^2

#law of exponents
3^2 * 3^4

3^(2+4)

#negative exponents mean reciprocal 
3^-1

1/3



```

# R can allow you to do many computations at once

```{r vectorization}
#using the power of R to solve 
#many problems at once! Vectorization
x = c(4,7,2,9) #this is a vector

x + 1

x^2

x%%2


```

# some mathematical calculations are impossible

```{r finite, infinite, nan}
#sometimes, a mathematical operation doesn't
#work as expected and produces strange results
c(-1, 0, 1) / 0
#These special values can cause issues in your
#analysis. You can check for them
x = c(-1,0,1) / 0
is.finite(x)
is.infinite(x)
is.nan(x)
is.na(x)
#these functions give you True and False output
#to help you understand where special values
#happen in your data, more on this later!


```

