---
title: 'Variable Types'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

# four modes of data 
```{r modes}

#numeric (can be doubles or integers)
w = c(11,12,13,14,15)
#character 
x = 'u'
#boolean / logical
y = c(T,F,T)
#complex
z = c(3+2i, 5+1i, -1+0i)
#you can check what mode your data are
mode(z)
mode(y)
mode(x)
mode(w)


```

# you can also screen a variable for a particular mode


```{r targeted screening}

is.numeric(z)
is.complex(y)
is.character(x)
is.logical(y)
class(x)

```

# there are also special error modes, do you remember them? 

```{r error modes}
#special values -Inf, Inf, NA, and NaN?
n = c(-1,0,1) / 0
#type your code here to check for special 
#values in n :)


```

## coersion of different variable types
```{r coersion}
x = 'u'
#you can also explicitly force data into a
#certain mode. 
as.logical(x) #0-> FALSE anything else -> TRUE
as.character(x)
as.complex(x)
as.numeric(x)
test = as.numeric(x)
is.na(test)
is.nan(test)
is.na(0/0)
is.nan(0/0)
#what's the difference between NA and NaN? 



```
