---
title: 'Vectors'
Section: 'Basic R Coding'
Author: "Adam Dede"
Course: "Data to Decisions: Master Statistics with R and tidyverse"
Course_URL: "..." 
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

library(tidyverse)



```

## vector indexing

```{r vector indexing}

w = c(11,12,13,14,15)
#numeric indexing


#colon indexing


#boolean indexing

#negative indexing



```
## inserting new values into a vector
```{r vector insertion}

length(w)
mode(w)
w = 
mode(w)

y = c('a', 'b', 'c')
y = 


```

## adding to the start or end of a vector
```{r start and end}

w = 



```

## recycling to populate a vector
```{r recycling}
x = 
y = 

x + y

x = vector('numeric', 10)



```
## using the colon operator
```{r colons}




#order of operations 
n=10

```
## some other useful ways to make vectors
```{r generate vecs}
seq(from = 1, to = 10, by = 2)


rep(c(1,12), 3)

# 3 6 9 3 6 9 3 6 9 3 6 9




```
