---
title: 'variability parametric'
author: "Adam Dede"
date: "2024-07-21"
output:
  html_document:
    toc: yes
    toc_float: yes
editor_options:
  chunk_output_type: console
---


## set environment

```{r message = FALSE, warning = FALSE}

# Set rendering parameters
knitr::opts_chunk$set(message = FALSE, warning = FALSE)

gitHubPath = 'C:\\Users\\Adam\\Documents\\GitHub\\MasterStatsUsingR\\'

library(tidyverse) # data manipulation and visualization
library(lubridate)

```

## grouping data to get counts of a category

```{r email data}

df = read.csv(paste0(gitHubPath, '\\data\\emailTimes.csv'))

df <- df %>% group_by(DayOfWeek, Month, DayOfMonth, Year) %>% 
  summarize(count = n(), .groups = 'drop')


```
## What can we do about days with zero emails? We still want to count these
```{r dealing with zeros}

df = read.csv(paste0(gitHubPath, '\\data\\emailTimes.csv'))
# Step 1: Generate a complete date range for the year 2024
start_date <- as.Date('2020-06-14')
end_date <- as.Date('2024-07-14')
complete_dates <- seq.Date(start_date, end_date, by = 'day')

# Step 2: Create a data frame with the complete date range and extract day of the week
calendar_df <- data.frame(
  Date = complete_dates,
  DayOfWeek = weekdays(complete_dates),
  Month = month(complete_dates),
  DayOfMonth = day(complete_dates),
  Year = year(complete_dates)
)

month_abbr <- c('Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec')

# Create a vector of abbreviated month names to numeric conversion
month_abbr_to_num <- function(month) {
  match(month, month_abbr)
}

# Convert example abbreviated month names to numeric
df$MonthNum <- month_abbr_to_num(df$Month)


df$Date = as.Date(paste(df$Year, df$MonthNum, df$DayOfMonth, sep = '-'))

# Step 3: Merge this with your data
df_full <- calendar_df %>%
  left_join(df, by = "Date", suffix = c("", "_remove"))  %>%
  replace_na(list(count = 0)) %>%
  select(which(!grepl("remove", names(.))))



```
## calculate the range of the data

``` {r norm range}

normDat = df$observed[df$dist == 'norm'] 

#what's the max value
max(normDat)-> maxVal
  
#what's the min value
min(normDat) -> minVal
  
#what's the max - min = range 
maxVal - minVal -> range


# Add vertical lines for the range
p + geom_vline(xintercept = minVal, linetype = 'solid', size = 3, color = 'red') + 
    geom_vline(xintercept = maxVal, linetype = 'solid', size = 3, color = 'red') 


```
## calculate the inter quartile range

``` {r norm IQR}

normDat = sort(normDat)

#25th percentile first quartile
median(normDat[1:(sampSize/2)]) -> q25
#75th percentile third quartile
median(normDat[(1+(sampSize/2)):sampSize]) -> q75

# Add vertical lines for the interquartile range
p + geom_vline(xintercept = q25, linetype = 'solid', size = 3, color = 'red') + 
    geom_vline(xintercept = q75, linetype = 'solid', size = 3, color = 'red') 
  

#alternatively box plots show the IQR by default: 
ggplot(data = data.frame('values' = normDat), 
       aes(y = values)) + geom_boxplot()

```

## calculate the mean absolute deviation 

``` {r norm MAD}

#MAD = sum(abs(x - mean(x))) / (n-1)

#mean val
mean(normDat) -> meanVal

#absolute deviations
abs(normDat - meanVal) -> abDevs

#sum and divide 
sum(abDevs) / (sampSize - 1) -> madVal

# Add vertical lines for the mad
p + geom_vline(xintercept = meanVal +madVal, linetype = 'solid', size = 3, color = 'red') + 
    geom_vline(xintercept = meanVal - madVal, linetype = 'solid', size = 3, color = 'red') 


```
## use summarize to get all the descriptive stats we know in one shot! 
```{r descriptives}
#mistake code: 
df  %>%
  group_by(dist) %>%
  summarise(mean_val = mean(observed),
            mode_val = Mode(round(observed,1)),
            median_val = median(observed), 
            var_val = var(observed), 
            sd_val = sd(observed), 
            ss_val = sum((observed - mean_val)^2),
            range_val = max(observed) - min(observed),
            Q_25 = quantile(observed, .25), 
            Q_75 = quantile(observed, .75),
            IQR_val = Q_75 - Q_25,
            mad_val = abs(observed - mean_val)/(sampSize-1)
              )-> descriptives 

#corrected: 
df  %>%
  group_by(dist) %>%
  summarise(mean_val = mean(observed),
            mode_val = Mode(round(observed,1)),
            median_val = median(observed), 
            var_val = var(observed), 
            sd_val = sd(observed), 
            ss_val = sum((observed - mean_val)^2),
            range_val = max(observed) - min(observed),
            Q_25 = quantile(observed, .25), 
            Q_75 = quantile(observed, .75),
            IQR_val = Q_75 - Q_25,
            mad_val = sum(abs(observed - mean_val))/(sampSize-1)
              )-> descriptives 

#let's round the values so that the table is easier to read
descriptives %>% mutate_if(is.numeric, ~ round(.,2)) -> roundedDes

#equivalently: 
descriptives %>% mutate_if(is.numeric, function(x) round(x,2)) -> roundedDes

kable(roundedDes)


```
